# -*- coding: utf-8 -*-

import csv
import pdb
import json

guardiannamesconversion = {
'Aberavon': 'Aberavon',
'Aberdeen North': 'Aberdeen North',
'Aberdeen South': 'Aberdeen South',
'Airdrie and Shotts': 'Airdrie and Shotts',
'Aldershot': 'Aldershot',
'Aldridge-Brownhills': 'Aldridge-Brownhills',
'Altrincham and Sale West': 'Altrincham and Sale West',
'Alyn and Deeside': 'Alyn and Deeside',
'Amber Valley': 'Amber Valley',
'Angus': 'Angus',
'Argyll and Bute': 'Argyll and Bute',
'Arundel and South Downs': 'Arundel and South Downs',
'Ashfield': 'Ashfield',
'Ashford': 'Ashford',
'Ashton Under Lyne': 'Ashton-under-Lyne',
'Aylesbury': 'Aylesbury',
'Ayrshire Central': 'Central Ayrshire',
'Banbury': 'Banbury',
'Banff and Buchan': 'Banff and Buchan',
'Barking': 'Barking',
'Barnsley Central': 'Barnsley Central',
'Barnsley East': 'Barnsley East',
'Barrow and Furness': 'Barrow and Furness',
'Basingstoke': 'Basingstoke',
'Bassetlaw': 'Bassetlaw',
'Bath': 'Bath',
'Batley and Spen': 'Batley and Spen',
'Battersea': 'Battersea',
'Beaconsfield': 'Beaconsfield',
'Beckenham': 'Beckenham',
'Bedford': 'Bedford',
'Belfast East': 'Belfast East',
'Belfast North': 'Belfast North',
'Belfast South': 'Belfast South',
'Belfast West': 'Belfast West',
'Berwick-upon-Tweed': 'Berwick-upon-Tweed',
'Bethnal Green and Bow': 'Bethnal Green and Bow',
'Beverley and Holderness': 'Beverley and Holderness',
'Bexhill and Battle': 'Bexhill and Battle',
'Bexleyheath and Crayford': 'Bexleyheath and Crayford',
'Birkenhead': 'Birkenhead',
'Birmingham Edgbaston': 'Birmingham, Edgbaston',
'Birmingham Erdington': 'Birmingham, Erdington',
'Birmingham Hall Green': 'Birmingham, Hall Green',
'Birmingham Hodge Hill': 'Birmingham, Hodge Hill',
'Birmingham Ladywood': 'Birmingham, Ladywood',
'Birmingham Northfield': 'Birmingham, Northfield',
'Birmingham Perry Barr': 'Birmingham, Perry Barr',
'Birmingham Selly Oak': 'Birmingham, Selly Oak',
'Birmingham Yardley': 'Birmingham, Yardley',
'Bishop Auckland': 'Bishop Auckland',
'Blackburn': 'Blackburn',
'Blackpool South': 'Blackpool South',
'Blaenau Gwent': 'Blaenau Gwent',
'Blaydon': 'Blaydon',
'Blyth Valley': 'Blyth Valley',
'Bognor Regis and Littlehampton': 'Bognor Regis and Littlehampton',
'Bolsover': 'Bolsover',
'Bolton North East': 'Bolton North East',
'Bolton South East': 'Bolton South East',
'Bolton West': 'Bolton West',
'Bootle': 'Bootle',
'Boston and Skegness': 'Boston and Skegness',
'Bosworth': 'Bosworth',
'Bournemouth East': 'Bournemouth East',
'Bournemouth West': 'Bournemouth West',
'Bracknell': 'Bracknell',
'Bradford South': 'Bradford South',
'Bradford West': 'Bradford West',
'Braintree': 'Braintree',
'Brecon and Radnorshire': 'Brecon and Radnorshire',
'Brent North': 'Brent North',
'Brentford and Isleworth': 'Brentford and Isleworth',
'Brentwood and Ongar': 'Brentwood and Ongar',
'Bridgend': 'Bridgend',
'Brigg and Goole': 'Brigg and Goole',
'Caerphilly': 'Caerphilly',
'Caithness, Sutherland and Easter Ross': 'Caithness, Sutherland and Easter Ross',
'Calder Valley': 'Calder Valley',
'Camberwell and Peckham': 'Camberwell and Peckham',
'Cambridge': 'Cambridge',
'Cannock Chase': 'Cannock Chase',
'Canterbury': 'Canterbury',
'Cardiff Central': 'Cardiff Central',
'Cardiff North': 'Cardiff North',
'Cardiff South and Penarth': 'Cardiff South and Penarth',
'Cardiff West': 'Cardiff West',
'Carlisle': 'Carlisle',
'Carmarthen East and Dinefwr': 'Carmarthen East and Dinefwr',
'Carmarthen West and Pembrokeshire South': 'Carmarthen West and South Pembrokeshire',
'Ayr, Carrick and Cumnock': 'Ayr, Carrick and Cumnock',
'Carshalton and Wallington': 'Carshalton and Wallington',
'Castle Point': 'Castle Point',
'Glenrothes': 'Glenrothes',
'Suffolk Central and Ipswich North': 'Central Suffolk and North Ipswich',
'Ceredigion': 'Ceredigion',
'Charnwood': 'Charnwood',
'Coatbridge, Chryston and Bellshill': 'Coatbridge, Chryston and Bellshill',
'Colchester': 'Colchester',
'Colne Valley': 'Colne Valley',
'Congleton': 'Congleton',
'Copeland': 'Copeland',
'Corby': 'Corby',
'Cotswolds, The': 'The Cotswolds',
'Coventry North East': 'Coventry North East',
'Coventry North West': 'Coventry North West',
'Coventry South': 'Coventry South',
'Crawley': 'Crawley',
'Crewe and Nantwich': 'Crewe and Nantwich',
'Croydon Central': 'Croydon Central',
'Croydon North': 'Croydon North',
'Croydon South': 'Croydon South',
'Cumbernauld, Kilsyth and Kirkintilloch East': 'Cumbernauld, Kilsyth and Kirkintilloch East',
'Ayrshire North and Arran': 'North Ayrshire and Arran',
'Cynon Valley': 'Cynon Valley',
'Dunbartonshire West': 'West Dunbartonshire',
'Dumfriesshire, Clydesdale and Tweeddale': 'Dumfriesshire, Clydesdale and Tweeddale',
'Dundee East': 'Dundee East',
'Dundee West': 'Dundee West',
'Dunfermline and Fife West': 'Dunfermline and West Fife',
'Durham North': 'North Durham',
'Durham North West': 'North West Durham',
'Ealing North': 'Ealing North',
'Ealing Southall': 'Ealing, Southall',
'Easington': 'Easington',
'Antrim East': 'East Antrim',
'Devon East': 'East Devon',
'East Ham': 'East Ham',
'Hampshire East': 'East Hampshire',
'East Kilbride, Strathaven and Lesmahagow': 'East Kilbride, Strathaven and Lesmahagow',
'Londonderry East': 'East Londonderry',
'East Lothian': 'East Lothian',
'Surrey East': 'East Surrey',
'Worthing East and Shoreham': 'East Worthing and Shoreham',
'Epsom and Ewell': 'Epsom and Ewell',
'Erewash': 'Erewash',
'Erith and Thamesmead': 'Erith and Thamesmead',
'Esher and Walton': 'Esher and Walton',
'Exeter': 'Exeter',
'Falkirk': 'Falkirk',
'Fareham': 'Fareham',
'Faversham and Kent Mid': 'Faversham and Mid Kent',
'Feltham and Heston': 'Feltham and Heston',
'Fermanagh and South Tyrone': 'Fermanagh and South Tyrone',
'Finchley and Golders Green': 'Finchley and Golders Green',
'Folkestone and Hythe': 'Folkestone and Hythe',
'Forest of Dean': 'Forest of Dean',
'Foyle': 'Foyle',
'Fylde': 'Fylde',
'Gainsborough': 'Gainsborough',
'Dumfries and Galloway': 'Dumfries and Galloway',
'Gedling': 'Gedling',
'Glasgow North West': 'Glasgow North West',
'Glasgow East': 'Glasgow East',
'Glasgow South': 'Glasgow South',
'Glasgow North': 'Glasgow North',
'Glasgow South West': 'Glasgow South West',
'Rutherglen and Hamilton West': 'Rutherglen and Hamilton West',
'Glasgow Central': 'Glasgow Central',
'Glasgow North East': 'Glasgow North East',
'Gloucester': 'Gloucester',
'Gordon': 'Gordon',
'Gosport': 'Gosport',
'Gower': 'Gower',
'Grantham and Stamford': 'Grantham and Stamford',
'Gravesham': 'Gravesham',
'Great Grimsby': 'Great Grimsby',
'Great Yarmouth': 'Great Yarmouth',
'Inverclyde': 'Inverclyde',
'Greenwich and Woolwich': 'Greenwich and Woolwich',
'Guildford': 'Guildford',
'Hackney North and Stoke Newington': 'Hackney North and Stoke Newington',
'Hackney South and Shoreditch': 'Hackney South and Shoreditch',
'Halesowen and Rowley Regis': 'Halesowen and Rowley Regis',
'Halifax': 'Halifax',
'Haltemprice and Howden': 'Haltemprice and Howden',
'Halton': 'Halton',
'Hammersmith': 'Hammersmith',
'Harborough': 'Harborough',
'Harlow': 'Harlow',
'Harrogate and Knaresborough': 'Harrogate and Knaresborough',
'Harrow East': 'Harrow East',
'Harrow West': 'Harrow West',
'Hartlepool': 'Hartlepool',
'Hornsey and Wood Green': 'Hornsey and Wood Green',
'Horsham': 'Horsham',
'Hove': 'Hove',
'Huddersfield': 'Huddersfield',
'Hull East': 'Kingston upon Hull East',
'Hull North': 'Kingston upon Hull North',
'Hull West and Hessle': 'Kingston upon Hull West and Hessle',
'Huntingdon': 'Huntingdon',
'Hyndburn': 'Hyndburn',
'Ilford North': 'Ilford North',
'Ilford South': 'Ilford South',
'Inverness, Nairn, Badenoch and Strathspey': 'Inverness, Nairn, Badenoch and Strathspey',
'Ipswich': 'Ipswich',
'Isle of Wight': 'Isle of Wight',
'Islington North': 'Islington North',
'Islington South and Finsbury': 'Islington South and Finsbury',
'Islwyn': 'Islwyn',
'Jarrow': 'Jarrow',
'Keighley': 'Keighley',
'Kensington': 'Kensington',
'Kettering': 'Kettering',
'Kilmarnock and Loudoun': 'Kilmarnock and Loudoun',
'Kingston and Surbiton': 'Kingston and Surbiton',
'Kingswood': 'Kingswood',
'Kirkcaldy and Cowdenbeath': 'Kirkcaldy and Cowdenbeath',
'Lagan Valley': 'Lagan Valley',
'Leeds Central': 'Leeds Central',
'Leeds East': 'Leeds East',
'Leeds North East': 'Leeds North East',
'Leeds North West': 'Leeds North West',
'Leeds West': 'Leeds West',
'Leicester East': 'Leicester East',
'Leicester South': 'Leicester South',
'Leicester West': 'Leicester West',
'Leigh': 'Leigh',
'Lewes': 'Lewes',
'Lewisham East': 'Lewisham East',
'Lewisham Deptford': 'Lewisham, Deptford',
'Leyton and Wanstead': 'Leyton and Wanstead',
'Lichfield': 'Lichfield',
'Lincoln': 'Lincoln',
'Linlithgow and Falkirk East': 'Linlithgow and East Falkirk',
'Liverpool Riverside': 'Liverpool, Riverside',
'Liverpool Walton': 'Liverpool, Walton',
'Liverpool Wavertree': 'Liverpool, Wavertree',
'Liverpool West Derby': 'Liverpool, West Derby',
'Livingston': 'Livingston',
'Llanelli': 'Llanelli',
'Loughborough': 'Loughborough',
'Louth and Horncastle': 'Louth and Horncastle',
'Ludlow': 'Ludlow',
'Luton North': 'Luton North',
'Luton South': 'Luton South',
'Macclesfield': 'Macclesfield',
'Maidenhead': 'Maidenhead',
'Maidstone and The Weald': 'Maidstone and The Weald',
'Makerfield': 'Makerfield',
'Manchester Central': 'Manchester Central',
'Manchester Gorton': 'Manchester, Gorton',
'Manchester Withington': 'Manchester, Withington',
'Mansfield': 'Mansfield',
'Meriden': 'Meriden',
'Merthyr Tydfil and Rhymney': 'Merthyr Tydfil and Rhymney',
'Bedfordshire Mid': 'Mid Bedfordshire',
'Dorset Mid and Poole North': 'Mid Dorset and North Poole',
'Norfolk Mid': 'Mid Norfolk',
'Sussex Mid': 'Mid Sussex',
'Ulster Mid': 'Mid Ulster',
'Worcestershire Mid': 'Mid Worcestershire',
'Middlesbrough': 'Middlesbrough',
'Middlesbrough South and Cleveland East': 'Middlesbrough South and East Cleveland',
'Midlothian': 'Midlothian',
'Mitcham and Morden': 'Mitcham and Morden',
'Mole Valley': 'Mole Valley',
'Monmouth': 'Monmouth',
'Montgomeryshire': 'Montgomeryshire',
'Moray': 'Moray',
'Morecambe and Lunesdale': 'Morecambe and Lunesdale',
'Dorset North': 'North Dorset',
'Down North': 'North Down',
'Bedfordshire North East': 'North East Bedfordshire',
'Cambridgeshire North East': 'North East Cambridgeshire',
'Derbyshire North East': 'North East Derbyshire',
'Fife North East': 'North East Fife',
'Hampshire North East': 'North East Hampshire',
'Hertfordshire North East': 'North East Hertfordshire',
'Norfolk North': 'North Norfolk',
'Shropshire North': 'North Shropshire',
'Swindon North': 'North Swindon',
'Thanet North': 'North Thanet',
'Tyneside North': 'North Tyneside',
'Warwickshire North': 'North Warwickshire',
'Cambridgeshire North West': 'North West Cambridgeshire',
'Hampshire North West': 'North West Hampshire',
'Leicestershire North West': 'North West Leicestershire',
'Norfolk North West': 'North West Norfolk',
'Wiltshire North': 'North Wiltshire',
'Paisley and Renfrewshire North': 'Paisley and Renfrewshire North',
'Paisley and Renfrewshire South': 'Paisley and Renfrewshire South',
'Pendle': 'Pendle',
'Penrith and The Border': 'Penrith and The Border',
'Perth and Perthshire North': 'Perth and North Perthshire',
'Peterborough': 'Peterborough',
'Pontypridd': 'Pontypridd',
'Poole': 'Poole',
'Portsmouth North': 'Portsmouth North',
'Portsmouth South': 'Portsmouth South',
'Preseli Pembrokeshire': 'Preseli Pembrokeshire',
'Preston': 'Preston',
'Pudsey': 'Pudsey',
'Putney': 'Putney',
'Reading East': 'Reading East',
'Reading West': 'Reading West',
'Redcar': 'Redcar',
'Redditch': 'Redditch',
'Reigate': 'Reigate',
'Rhondda': 'Rhondda',
'Ribble Valley': 'Ribble Valley',
'Richmond (Yorks)': 'Richmond (Yorks)',
'Richmond Park': 'Richmond Park',
'Rochdale': 'Rochdale',
'Rochford and Southend East': 'Rochford and Southend East',
'Romford': 'Romford',
'Ross, Skye and Lochaber': 'Ross, Skye and Lochaber',
'Rossendale and Darwen': 'Rossendale and Darwen',
'Rother Valley': 'Rother Valley',
'Rotherham': 'Rotherham',
'Berwickshire, Roxburgh and Selkirk': 'Berwickshire, Roxburgh and Selkirk',
'Runnymede and Weybridge': 'Runnymede and Weybridge',
'Rushcliffe': 'Rushcliffe',
'Rutland and Melton': 'Rutland and Melton',
'Saffron Walden': 'Saffron Walden',
'Salisbury': 'Salisbury',
'Scarborough and Whitby': 'Scarborough and Whitby',
'Scunthorpe': 'Scunthorpe',
'Sedgefield': 'Sedgefield',
'Sevenoaks': 'Sevenoaks',
'Sheffield Central': 'Sheffield Central',
'Sheffield Hallam': 'Sheffield, Hallam',
'Sheffield Heeley': 'Sheffield, Heeley',
'Sherwood': 'Sherwood',
'Shipley': 'Shipley',
'Shrewsbury and Atcham': 'Shrewsbury and Atcham',
'Sittingbourne and Sheppey': 'Sittingbourne and Sheppey',
'Skipton and Ripon': 'Skipton and Ripon',
'Sleaford and North Hykeham': 'Sleaford and North Hykeham',
'Slough': 'Slough',
'Solihull': 'Solihull',
'Somerton and Frome': 'Somerton and Frome',
'Antrim South': 'South Antrim',
'Cambridgeshire South': 'South Cambridgeshire',
'Derbyshire South': 'South Derbyshire',
'Dorset South': 'South Dorset',
'Down South': 'South Down',
'Cambridgeshire South East': 'South East Cambridgeshire',
'Cornwall South East': 'South East Cornwall',
'South Holland and The Deepings': 'South Holland and The Deepings',
'Norfolk South': 'South Norfolk',
'South Ribble': 'South Ribble',
'South Shields': 'South Shields',
'Staffordshire South': 'South Staffordshire',
'Suffolk South': 'South Suffolk',
'Swindon South': 'South Swindon',
'Thanet South': 'South Thanet',
'Bedfordshire South West': 'South West Bedfordshire',
'Devon South West': 'South West Devon',
'Hertfordshire South West': 'South West Hertfordshire',
'Norfolk South West': 'South West Norfolk',
'Surrey South West': 'South West Surrey',
'Southampton Itchen': 'Southampton, Itchen',
'Southampton Test': 'Southampton, Test',
'Southend West': 'Southend West',
'Southport': 'Southport',
'Stourbridge': 'Stourbridge',
'Strangford': 'Strangford',
'Stratford-on-Avon': 'Stratford-on-Avon',
'Dunbartonshire East': 'East Dunbartonshire',
'Streatham': 'Streatham',
'Stretford and Urmston': 'Stretford and Urmston',
'Stroud': 'Stroud',
'Suffolk Coastal': 'Suffolk Coastal',
'Surrey Heath': 'Surrey Heath',
'Sutton Coldfield': 'Sutton Coldfield',
'Sutton and Cheam': 'Sutton and Cheam',
'Swansea East': 'Swansea East',
'Swansea West': 'Swansea West',
'Tamworth': 'Tamworth',
'Tatton': 'Tatton',
'Telford': 'Telford',
'Tewkesbury': 'Tewkesbury',
'Wrekin, The': 'The Wrekin',
'Thurrock': 'Thurrock',
'Tiverton and Honiton': 'Tiverton and Honiton',
'Tonbridge and Malling': 'Tonbridge and Malling',
'Tooting': 'Tooting',
'Torbay': 'Torbay',
'Torfaen': 'Torfaen',
'Devon West and Torridge': 'Torridge and West Devon',
'Totnes': 'Totnes',
'Tottenham': 'Tottenham',
'Tunbridge Wells': 'Tunbridge Wells',
'Twickenham': 'Twickenham',
'Tynemouth': 'Tynemouth',
'Upper Bann': 'Upper Bann',
'Vale of Clwyd': 'Vale of Clwyd',
'Vale of Glamorgan': 'Vale of Glamorgan',
'Vauxhall': 'Vauxhall',
'Wakefield': 'Wakefield',
'Wallasey': 'Wallasey',
'Walsall North': 'Walsall North',
'Walsall South': 'Walsall South',
'Walthamstow': 'Walthamstow',
'Wansbeck': 'Wansbeck',
'Wantage': 'Wantage',
'Warley': 'Warley',
'Warrington North': 'Warrington North',
'Warrington South': 'Warrington South',
'Warwick and Leamington': 'Warwick and Leamington',
'Watford': 'Watford',
'Waveney': 'Waveney',
'Wealden': 'Wealden',
'Weaver Vale': 'Weaver Vale',
'Wellingborough': 'Wellingborough',
'Wells': 'Wells',
'Welwyn Hatfield': 'Welwyn Hatfield',
'Aberdeenshire West and Kincardine': 'West Aberdeenshire and Kincardine',
'West Bromwich East': 'West Bromwich East',
'West Bromwich West': 'West Bromwich West',
'Dorset West': 'West Dorset',
'West Ham': 'West Ham',
'Lancashire West': 'West Lancashire',
'Suffolk West': 'West Suffolk',
'Tyrone West': 'West Tyrone',
'Worcestershire West': 'West Worcestershire',
'Na h-Eileanan an Iar': 'Na h-Eileanan an Iar',
'Westminster North': 'Westminster North',
'Westmorland and Lonsdale': 'Westmorland and Lonsdale',
'Weston-Super-Mare': 'Weston-Super-Mare',
'Wigan': 'Wigan',
'Wimbledon': 'Wimbledon',
'Winchester': 'Winchester',
'Windsor': 'Windsor',
'Wirral South': 'Wirral South',
'Wirral West': 'Wirral West',
'Witney': 'Witney',
'Woking': 'Woking',
'Wokingham': 'Wokingham',
'Wolverhampton North East': 'Wolverhampton North East',
'Wolverhampton South East': 'Wolverhampton South East',
'Wolverhampton South West': 'Wolverhampton South West',
'Worcester': 'Worcester',
'Workington': 'Workington',
'Worthing West': 'Worthing West',
'Wrexham': 'Wrexham',
'Wycombe': 'Wycombe',
'Wyre Forest': 'Wyre Forest',
'Wythenshawe and Sale East': 'Wythenshawe and Sale East',
'Yeovil': 'Yeovil',
'Ynys Mon': 'Ynys Mon',
'Yorkshire East': 'East Yorkshire',
'Aberconwy': 'Aberconwy',
'Arfon': 'Arfon',
'Basildon South and Thurrock East': 'South Basildon and East Thurrock',
'Basildon and Billericay': 'Basildon and Billericay',
'Bermondsey and Old Southwark': 'Bermondsey and Old Southwark',
'Blackley and Broughton': 'Blackley and Broughton',
'Blackpool North and Cleveleys': 'Blackpool North and Cleveleys',
'Bradford East': 'Bradford East',
'Brent Central': 'Brent Central',
'Bridgwater and Somerset West': 'Bridgwater and West Somerset',
'Broadland': 'Broadland',
'Camborne and Redruth': 'Camborne and Redruth',
'Chelsea and Fulham': 'Chelsea and Fulham',
'Chippenham': 'Chippenham',
'Clacton': 'Clacton',
'Dagenham and Rainham': 'Dagenham and Rainham',
'Derbyshire Dales': 'Derbyshire Dales',
'Derbyshire Mid': 'Mid Derbyshire',
'Devon Central': 'Central Devon',
'Dwyfor Meirionnydd': 'Dwyfor Meirionnydd',
'Ealing Central and Acton': 'Ealing Central and Acton',
'Elmet and Rothwell': 'Elmet and Rothwell',
'Filton and Bradley Stoke': 'Filton and Bradley Stoke',
'Garston and Halewood': 'Garston and Halewood',
'Gateshead': 'Gateshead',
'Gillingham and Rainham': 'Gillingham and Rainham',
'Hampstead and Kilburn': 'Hampstead and Kilburn',
'Harwich and Essex North': 'Harwich and North Essex',
'Hereford and Herefordshire South': 'Hereford and South Herefordshire',
'Herefordshire North': 'North Herefordshire',
'Hornchurch and Upminster': 'Hornchurch and Upminster',
'Houghton and Sunderland South': 'Houghton and Sunderland South',
'Kenilworth and Southam': 'Kenilworth and Southam',
'Knowsley': 'Knowsley',
'Lancaster and Fleetwood': 'Lancaster and Fleetwood',
'Leicestershire South': 'South Leicestershire',
'Lewisham West and Penge': 'Lewisham West and Penge',
'Maldon': 'Maldon',
'Meon Valley': 'Meon Valley',
'Milton Keynes North': 'Milton Keynes North',
'Milton Keynes South': 'Milton Keynes South',
'Morley and Outwood': 'Morley and Outwood',
'Newton Abbot': 'Newton Abbot',
'Normanton, Pontefract and Castleford': 'Normanton, Pontefract and Castleford',
'Northamptonshire South': 'South Northamptonshire',
'Penistone and Stocksbridge': 'Penistone and Stocksbridge',
'Plymouth Moor View': 'Plymouth, Moor View',
'Plymouth Sutton and Devonport': 'Plymouth, Sutton and Devonport',
'Poplar and Limehouse': 'Poplar and Limehouse',
'Rayleigh and Wickford': 'Rayleigh and Wickford',
'Rochester and Strood': 'Rochester and Strood',
'Romsey and Southampton North': 'Romsey and Southampton North',
'Rugby': 'Rugby',
'Ruislip, Northwood and Pinner': 'Ruislip, Northwood and Pinner',
'Salford and Eccles': 'Salford and Eccles',
'Sefton Central': 'Sefton Central',
'Selby and Ainsty': 'Selby and Ainsty',
'Sheffield Brightside and Hillsborough': 'Sheffield, Brightside and Hillsborough',
'Sheffield South East': 'Sheffield South East',
'Somerset North': 'North Somerset',
'Somerset North East': 'North East Somerset',
'St Austell and Newquay': 'St Austell and Newquay',
'St Helens South and Whiston': 'St Helens South and Whiston',
'Sunderland Central': 'Sunderland Central',
'Taunton Deane': 'Taunton Deane',
'Thirsk and Malton': 'Thirsk and Malton',
'Thornbury and Yate': 'Thornbury and Yate',
'Truro and Falmouth': 'Truro and Falmouth',
'Uxbridge and Ruislip South': 'Uxbridge and South Ruislip',
'Washington and Sunderland West': 'Washington and Sunderland West',
'Wentworth and Dearne': 'Wentworth and Dearne',
'Wiltshire South West': 'South West Wiltshire',
'Witham': 'Witham',
'Worsley and Eccles South': 'Worsley and Eccles South',
'Wyre and Preston North': 'Wyre and Preston North',
'York Central': 'York Central',
'York Outer': 'York Outer',
'Eastbourne': 'Eastbourne',
'Eastleigh': 'Eastleigh',
'Renfrewshire East': 'East Renfrewshire',
'Eddisbury': 'Eddisbury',
'Edinburgh East': 'Edinburgh East',
'Edinburgh North and Leith': 'Edinburgh North and Leith',
'Edinburgh South West': 'Edinburgh South West',
'Edinburgh South': 'Edinburgh South',
'Edinburgh West': 'Edinburgh West',
'Edmonton': 'Edmonton',
'Ellesmere Port and Neston': 'Ellesmere Port and Neston',
'Eltham': 'Eltham',
'Enfield North': 'Enfield North',
'Enfield Southgate': 'Enfield, Southgate',
'Epping Forest': 'Epping Forest',
'Brighton Kemptown': 'Brighton, Kemptown',
'Brighton Pavilion': 'Brighton, Pavilion',
'Bristol East': 'Bristol East',
'Bristol North West': 'Bristol North West',
'Bristol South': 'Bristol South',
'Bristol West': 'Bristol West',
'Bromley and Chislehurst': 'Bromley and Chislehurst',
'Bromsgrove': 'Bromsgrove',
'Broxbourne': 'Broxbourne',
'Broxtowe': 'Broxtowe',
'Buckingham': 'Buckingham',
'Burnley': 'Burnley',
'Burton': 'Burton',
'Bury North': 'Bury North',
'Bury South': 'Bury South',
'Bury St Edmunds': 'Bury St Edmunds',
'Motherwell and Wishaw': 'Motherwell and Wishaw',
'Neath': 'Neath',
'New Forest East': 'New Forest East',
'New Forest West': 'New Forest West',
'Newark': 'Newark',
'Newbury': 'Newbury',
'Newcastle upon Tyne Central': 'Newcastle upon Tyne Central',
'Newcastle upon Tyne East': 'Newcastle upon Tyne East',
'Newcastle upon Tyne North': 'Newcastle upon Tyne North',
'Newcastle-under-Lyme': 'Newcastle-under-Lyme',
'Newport East': 'Newport East',
'Newport West': 'Newport West',
'Newry and Armagh': 'Newry and Armagh',
'Antrim North': 'North Antrim',
'Cornwall North': 'North Cornwall',
'Devon North': 'North Devon',
'Chatham and Aylesford': 'Chatham and Aylesford',
'Cheadle': 'Cheadle',
'Chelmsford': 'Chelmsford',
'Cheltenham': 'Cheltenham',
'Chesham and Amersham': 'Chesham and Amersham',
'Chesterfield': 'Chesterfield',
'Chichester': 'Chichester',
'Chingford and Woodford Green': 'Chingford and Woodford Green',
'Chipping Barnet': 'Chipping Barnet',
'Chorley': 'Chorley',
'Christchurch': 'Christchurch',
'Cities of London and Westminster': 'Cities of London and Westminster',
'Chester, City of': 'City of Chester',
'Durham, City of': 'City of Durham',
'Cleethorpes': 'Cleethorpes',
'Clwyd South': 'Clwyd South',
'Clwyd West': 'Clwyd West',
'Lanark and Hamilton East': 'Lanark and Hamilton East',
'Darlington': 'Darlington',
'Dartford': 'Dartford',
'Daventry': 'Daventry',
'Delyn': 'Delyn',
'Denton and Reddish': 'Denton and Reddish',
'Derby North': 'Derby North',
'Derby South': 'Derby South',
'Devizes': 'Devizes',
'Dewsbury': 'Dewsbury',
'Don Valley': 'Don Valley',
'Doncaster Central': 'Doncaster Central',
'Doncaster North': 'Doncaster North',
'Dover': 'Dover',
'Dudley North': 'Dudley North',
'Dudley South': 'Dudley South',
'Dulwich and West Norwood': 'Dulwich and West Norwood',
'Northampton North': 'Northampton North',
'Northampton South': 'Northampton South',
'Norwich North': 'Norwich North',
'Norwich South': 'Norwich South',
'Nottingham East': 'Nottingham East',
'Nottingham North': 'Nottingham North',
'Nottingham South': 'Nottingham South',
'Nuneaton': 'Nuneaton',
'Ochil and Perthshire South': 'Ochil and South Perthshire',
'Ogmore': 'Ogmore',
'Old Bexley and Sidcup': 'Old Bexley and Sidcup',
'Oldham West and Royton': 'Oldham West and Royton',
'Orkney and Shetland': 'Orkney and Shetland',
'Orpington': 'Orpington',
'Oxford East': 'Oxford East',
'Oxford West and Abingdon': 'Oxford West and Abingdon',
'Spelthorne': 'Spelthorne',
'St Albans': 'St Albans',
'St Helens North': 'St Helens North',
'St Ives': 'St Ives',
'Stafford': 'Stafford',
'Staffordshire Moorlands': 'Staffordshire Moorlands',
'Stalybridge and Hyde': 'Stalybridge and Hyde',
'Stevenage': 'Stevenage',
'Stirling': 'Stirling',
'Stockport': 'Stockport',
'Stockton North': 'Stockton North',
'Stockton South': 'Stockton South',
'Stoke-on-Trent Central': 'Stoke-on-Trent Central',
'Stoke-on-Trent North': 'Stoke-on-Trent North',
'Stoke-on-Trent South': 'Stoke-on-Trent South',
'Stone': 'Stone',
'Hastings and Rye': 'Hastings and Rye',
'Havant': 'Havant',
'Hayes and Harlington': 'Hayes and Harlington',
'Hazel Grove': 'Hazel Grove',
'Hemel Hempstead': 'Hemel Hempstead',
'Hemsworth': 'Hemsworth',
'Hendon': 'Hendon',
'Henley': 'Henley',
'Hertford and Stortford': 'Hertford and Stortford',
'Hertsmere': 'Hertsmere',
'Hexham': 'Hexham',
'Heywood and Middleton': 'Heywood and Middleton',
'High Peak': 'High Peak',
'Hitchin and Harpenden': 'Hitchin and Harpenden',
'Holborn and St Pancras': 'Holborn and St Pancras',
'Oldham East and Saddleworth': 'Oldham East and Saddleworth'
}

partynameconversion = {
  'Lab': 'Labour Party',
  'LD': 'Liberal Democrats',
  'C': 'Conservative Party',
  'PC': 'Plaid Cymru',
  'UKIP': 'UK Independence Party (UKIP)',
  'SNP': 'Scottish National Party',
  'Green': 'Green Party',
  'TUSC': 'Trade Unionist and Socialist Coalition',
  'Ind': 'Independent',
  'Eng Dem': 'English Democrats',
  'CPA': 'Christian Peoples Alliance',
  'Alliance': 'Alliance - Alliance Party of Northern Ireland',
  'SF': u'Sinn Féin',
  'DUP': 'Democratic Unionist Party - D.U.P.',
  'SDLP': 'SDLP (Social Democratic & Labour Party)',
  'Respect': 'The Respect Party',
  'Lab Co-op': 'Labour Party'
}

def switch_name(name):
  ar = name.split()
  return ar[1] + ' ' + ar[0][:-1]

#for name in guardiannames2:
#  if not name in guardiannamesconversion:
#    print name
#  convertedname = guardiannamesconversion[name]
#  if not convertedname in yourcandlist:
#    print convertedname

csvfile = open('guardian.csv', 'rb')
r = csv.reader(csvfile)
oldareaname = '#fail'
data = []
newrow = {}
for row in r:
  areaname = guardiannamesconversion[row[2]]
  if areaname != oldareaname:
    data.append(newrow)
    newrow = {}
    newrow['name'] = areaname
    newrow['parties'] = {}
    oldareaname = areaname
  party = row[4]
  if party in partynameconversion:
    p = partynameconversion[party]
  else:
    p = party
  newrow['parties'][p] = { 'percentage': float(row[6]),
    'name': switch_name(row[3]),
    'elected': row[8] is '*' }
data.append(newrow)
    
print json.dumps(data,indent=2,sort_keys=True)


