class CandidatesController < ApplicationController
  require 'uk_postcode'
  require 'json'
  require 'open-uri'
  require 'twitter'

  POLICY_AREAS = [ 'The NHS', 'Economy and taxes', 'Immigration', 'Benefits and pensions', 'Law and order', 'Environment' ]
  PARTY_CONSTANTS = { 
    'Conservative Party' => { 
      'The NHS' => [ [ 'Make GPs available seven days a week by 2020. Recruit 5,000 more doctors.', 'https://www.conservatives.com/SecuringABetterFuture/GoodServices.aspx' ], [ 'Spend extra £2bn on frontline health services.', 'http://www.bbc.co.uk/news/uk-politics-30265833' ] ],
      'Economy and taxes' => [ [ 'Secure budget surplus by 2019-20. Instead of raising taxes, cut spending, while increasing NHS spending.', 'http://press.conservatives.com/post/98719492085/george-osborne-speech-to-conservative-party' ], [ 'Cut income tax of 30 million people by 2020. Raise tax-free income allowance and limit for 40px tax rate.' ] ],
      'Immigration' => [ [ 'Require European jobseekers to leave if they are unemployed after 6 months. Renegotiate the rules for free movement within the EU. Make migrants wait 4 years before claiming certain benefits or social housing.', 'http://press.conservatives.com/post/103802921280/david-cameron-speech-on-immigration' ], [ 'Lower annual net immigration to below 100,000 (currently 243,00).', 'https://www.conservatives.com/Plan/CapWelfareReduceImmigration.aspx' ] ],
      'Benefits and pensions' => [ [ 'Cut the maximum a household can claim yearly from £26,000 to £23,000. Require young people to participate in "community projects" after six months on Jobseeker\'s Allowance. Freeze increases of benefits for working-age people for two years, to save £3bn.', 'http://press.conservatives.com/post/108155759640/david-cameron-britain-living-within-its-means' ] ],
      'Law and order' => [ [ 'Replace Human Rights Act with Bill of Rights to give power to UK courts. New laws to make it easier to collect information about internet activity of suspected criminals. Introduce special orders for groups inciting hatred, and to stop public speech of "disruptive" individuals.', 'http://press.conservatives.com/post/98799073410/theresa-may-speech-to-conservative-party' ] ],
      'Environment' => 'For conservatives, the environment is very important',
      'party_image_uri' => '/assets/party_conservative.png'
    },
    'Labour Party' => {
      'The NHS' => [ [ 'Commit extra £4.5bn to NHS.', 'http://www.nlmanagedservices.co.uk/extra-funding-for-nhs/' ], [ 'Ensure that patients get GP appointment within 48 hours. End "creeping privatisation" of the NHS. Integrate health and social services into "whole-person care".', 'http://www.labour.org.uk/issues/detail/gp-48-hour-guarantee' ] ],
      'Economy and taxes' => [ [ 'Get budget into surplus and national debt falling in next parliament, with spending cuts and tax changes.', 'http://www.edballs.co.uk/blog/?p=5733' ], ["Reintroduce 50p top rate of income tax for earnings over £150,000, and 10p rate for 24 million people. Tax \"mansions\" and bankers' bonuses. Freeze energy prices and rail fares until 2017.", 'http://press.labour.org.uk/post/74420740121/ed-balls-announces-binding-fiscal-commitment-that' ] ],
      'Immigration' => [ ['Reduce low-skilled migration with "smarter targets", while ensuring university students and high-skilled workers can migrate. Establish stronger border control to reduce illegal immigration, with "proper" entry and exit checks. Increase fines for employing illegal immigrants, and outlaw employment agencies recruiting only abroad.', 'http://press.labour.org.uk/post/98301589749/speech-by-yvette-cooper-mp-to-labours-annual' ] ],
      'Benefits and pensions' => [ [ 'Increase minimum wage to £8-an-hour by 2020. Repeal the "bedroom tax".', 'http://www.labour.org.uk/issues/detail/social-security' ], [ 'Double the length of paid paternity leave, and increase statutory paternity pay to £260 a week.', 'http://www.bbc.co.uk/news/uk-politics-31253409' ] ],
      'Law and order' => [ [ 'Give local residents say in crime fighting priorities. Spend more money on frontline policing to prevent reduction in officer numbers. To combat extremism, bring back Control Orders and Prevent strategy.', 'http://www.labour.org.uk/issues/detail/crime-and-policing' ] ],
      'Environment' => 'For labour, the environment is very important',
      'party_image_uri' => '/assets/party_labour.png'
    },
    'Liberal Democrats' => { 
      'The NHS' => [ [ 'Increase spending on NHS rises in line with growth of the economy, funded by increasing capital tax on high earners. Half of extra spending targeted at mental health. Ensure therapy is available within 18 weeks.', 'http://www.libdems.org.uk/mental-health-stigma' ] ],
      'Economy and taxes' => [ [ 'Eliminate budget deficit by 2018, with spending cuts and tax changes. Raise tax-free income allowance to £12,500.', 'http://www.libdems.org.uk/liberal_democrats_will_raise_tax_free_allowance_in_the_first_year_of_the_next_parliament' ], [ 'Create "mansion tax" on property worth £3m, and capital gains tax on profits from second homes and shares.', 'http://www.libdems.org.uk/get_the_facts_mansion_tax' ] ],
      'Immigration' => [ [ 'Reintroduce exit checks at UK borders, so the government can identify people overstaying their visa. Mandate people on unemployment benefits to take an English test, and require those who fail to attend English classes.', 'http://www.libdems.org.uk/nick_clegg_s_immigration_speech' ] ],
      'Benefits and pensions' => [ [ 'No Winter Fuel Payment and free TV license for pensioners with high earnings. Rather than direct sanctions, introduce a "yellow card" system to deal with benefit claimants that break the rules.', 'http://www.libdemvoice.org/steve-webb-lib-dems-will-introduce-fair-warning-for-jobseekers-who-break-benefit-rules-before-sanctions-imposed-42030.html' ] ],
      'Law and order' => [ [ 'Instead of prison sentences for drug possession, give non-custodial sentencs and medical treatment. Pass a Digital Bill of Rights to protect people from unwarranted intrusion and grant them more control over their own data. Make police in some areas wear body cameras to make \'stop and search\' more accountable.', 'http://www.libdems.org.uk/protecting_your_privacy_online_with_a_digital_bill_of_rights' ] ],
      'Environment' => 'For libdems, the environment is very important',
      'party_image_uri' => '/assets/party_libdem.png'
    },
    'Green Party' => {
      'The NHS' => [ [ 'Divert funding form centralised facilities to community healthcare, prevention and health promotion. End privatisation and prescription charges, and create medicines agency that sets drug prices. Ensure NHS funding through earmarked NHS tax.', 'http://policy.greenparty.org.uk/he.html' ] ],
      'Economy and taxes' => [ [ 'Renationalise railways and energy companies.', 'http://greenparty.org.uk/news/2013/02/11/renationalise-rail-says-green-party-leader/' ], [ "Set up citizen's income, an unconditional benefit for basic needs. Stop banks from being able to create new money. Work to end dependency on economic growth.", 'http://policy.greenparty.org.uk/ec.html' ] ],
      'Immigration' => [ [ 'Reduce UK immigration controls over time. Migrants illegally in the UK for over five years will be allowed to remain unless they pose a serious danger to public safety.', 'http://policy.greenparty.org.uk/mg.html' ], [ 'Increase legal rights of asylum seekers.', 'http://policy.greenparty.org.uk/ra.html' ] ],
      'Benefits and pensions' => [ [ 'Reform benefit system with Citizen\'s income, an unconditional fixed money transfer.', 'http://greenparty.org.uk/news/2014/11/03/green-party-condemns-three-pronged-government-attack-on-sick-and-disabled/' ], [ 'Before that, ban zero hours contracts, stop current work capability assessments, and restore the level of the former disability living allowance.', 'http://policy.greenparty.org.uk/ec.html' ] ],
      'Law and order' => [ [ 'Decriminalise cannabis and prostitution. Eemove prison sentences for possession of other drugs. Ensure terror suspects have same legal rights as those suspected of other crimes.', 'http://policy.greenparty.org.uk/rr.html' ] ],
      'Environment' => 'For greens, the environment is very important',
      'party_image_uri' => '/assets/party_green.png'
    },
    'UK Independence Party (UKIP)' => {
      'The NHS' => [ [ 'Extra £3bn to NHS, funded by quitting EU and "middle management" cuts. Keep NHS free "at point of delivery". Require migrants who have not been in UK for five years to have private medical insurance. Bring back state-enrolled nurses and return powers to matrons.', 'http://www.ukip.org/ukip_pledge_an_extra_3_billion_for_the_nhs' ] ],
      'Economy and taxes' => [ [ 'Increase tax-free personal allowance to £13,500, and reduce tax paid at above £42,000. Abolish inheritance tax, and set up turnover tax on large businesses. Cut the foreign aid budget adn EU membership fees.', 'http://www.ukip.org/policies_for_people' ] ],
      'Immigration' => [ [ 'Choose immigrants based on a system of points, reflecting skills needed for work in the country. Apply points system to both EU and non-EU immigrants. Reduce net immigration to 50,000 people a year. Make language skill tests for residence permits harder.', 'http://www.ukip.org/steven_woolfe_ukip_s_ethical_migration_policy' ], [ 'People who currently are in the UK legally would not be deported, were the UK to leave the EU.', '' ] ],
      'Benefits and pensions' => [ [ 'No child benefit for children after the second one, or for children outside of Britain. Repeal the "bedroom tax", as it is unfair. No permanent residence for migrants that are unable to support themselves for at least five years.', 'http://www.ukip.org/policies_for_people' ] ],
      'Law and order' => [ [ 'Replace the Human Rights Act with UK Bill of Rights, and withdraw from European Arrest Warrant, that coordinates extradition of criminals between European countries. No votes for prisoners, and as a rule prison sentences should be served in their full length.', 'http://www.ukip.org/policies_for_people' ] ],
      'Environment' => 'For ukip, the environment is very important',
      'party_image_uri' => '/assets/party_ukip.png'
    },
    'Scottish National Party' => {
      'The NHS' => [ [ 'For Scottish NHS, increase yearly spending on NHS by more than inflation. Reduce number of senior managers by 25%. Streamline the work of health boards.', 'http://votesnp.com/campaigns/SNP_Manifesto_2011_lowRes.pdf' ] ],
      'Economy and taxes' => [ [ 'Create an international bank tax and limits to industry bonuses. Invest in offshore wind farms.', 'http://www.snp.org/?q=media-centre/news/2014/nov/uk-government-needs-invest-offshore-wind' ], [ 'No to oil drilling and fracking beneath homes, as in the Infrastructure Bill.', 'http://www.snp.org/?q=media-centre/news/2014/aug/westminsters-gung-ho-fracking-plans-condemnedo' ] ],
      'Immigration' => [ [ 'Give the devolved Scottish government control over immigration to Scotland. Use a Canadian-style "earned citizenship system" to attract high-skilled workers.', '' ] ],
      'Benefits and pensions' => [ [ 'In 2010, SNP opposed cuts to in-work benefits, and supported extending paternity leave. It suggested a maximum combined withdrawal rate for benefits, and reforms in employment support allowance and cold weather payments.', 'http://www.politicsresources.net/area/uk/ge10/man/parties/SNP.pdf' ] ],
      'Law and order' => 'No information about SNP and law and order yet',
      'Environment' => 'For SNP, the environment is very important',
    },
    'Plaid Cymru' => {
      'The NHS' => [ [ 'For Welsh NHS, recruit 1,000 extra doctors over two terms of government. Offer incentives, improved education, and international recruitment to employ doctors to areas and specilisations where there are shortages.', 'http://www.partyof.wales/uploads/1000_doctors_PDF_Eng_.pdf' ] ],
      'Economy and taxes' => [ [ 'Set living wage as minimum wage. Establish publicly owned energy companies, a business investment bank, and higher education focused on green energy. Devolve power over institutions such as the Bank of England.', 'http://www.english.plaidcymru.org/uploads/Articles_and_reports/Greenprint_Cynllun_Gwyrdd.pdf' ] ],
      'Immigration' => [ [ 'Opposes a choice of immigrants following a "point-based system", as it would not reflect Welsh needs. Asylum seekers should be able to work in Wales while waiting for their status decision. UK government should close "detention centres".', 'http://www.partyof.wales/our-vision-for-a-better-society/?force=1' ] ],
      'Benefits and pensions' => [ [ 'Move away from complex and expensive means testing for child-related benefits. Introduce a living pension for those aged 80 and over.', 'http://www.partyof.wales/our-vision-for-a-better-society/?force=1' ] ],
      'Law and order' => [ [ 'Replace Anti-Social Behaviour Orders with restorative justice. Create a Welsh Youth Justice Board. Encourage a debate on future of drug enforcement laws.', 'http://www.plaid.cymru/g_downloads/2011-06-13-29-2-safer-communities.pdf' ] ],
      'Environment' => 'For plaid cymru, the environment is very important',
    },
    'Default' => {
      'The NHS' => 'No information about NHS for this party yet',
      'Economy and taxes' => 'No information about economic policy for this party yet',
      'Immigration' => 'No information about immigration for this party yet',
      'Benefits and pensions' => 'No information about benefits and pensions for this party yet',
      'Law and order' => 'No information about law and order for this party yet',
      'Environment' => 'No information about environment yet'
    }
  }

  TWITTER_LIST = {
    66101 => "aberavon",
    66085 => "aberconwy",
    14398 => "aberdeen-north",
    14399 => "aberdeen-south",
    14400 => "airdrie-and-shotts",
    65730 => "aldershot",
    65773 => "aldridge-brownhills",
    65892 => "altrincham-and-sale-west",
    66103 => "alyn-and-deeside",
    65809 => "amber-valley",
    14401 => "angus",
    66108 => "arfon",
    14402 => "argyll-and-bute",
    65784 => "arundel-and-south-downs",
    65895 => "ashfield",
    65811 => "ashford",
    66056 => "ashton-under-lyne",
    65739 => "aylesbury",
    14403 => "ayr-carrick-and-cumnock",
    66008 => "banbury",
    14404 => "banff-and-buchan",
    65662 => "barking",
    65665 => "barnsley-central",
    66012 => "barnsley-east",
    66006 => "barrow-and-furness",
    65898 => "basildon-and-billericay",
    65623 => "basingstoke",
    65711 => "bassetlaw",
    65798 => "bath",
    65751 => "batley-and-spen",
    65731 => "battersea",
    65687 => "beaconsfield",
    65725 => "beckenham",
    65561 => "bedford",
    66124 => "belfast-east",
    66125 => "belfast-north",
    66126 => "belfast-south",
    66127 => "belfast-west",
    65689 => "bermondsey-and-old-southw",
    65726 => "berwick-upon-tweed",
    14405 => "berwickshire-roxburgh-and",
    65853 => "bethnal-green-and-bow",
    65934 => "beverley-and-holderness",
    65845 => "bexhill-and-battle",
    65611 => "bexleyheath-and-crayford",
    65581 => "birkenhead",
    65931 => "birmingham-edgbaston",
    65667 => "birmingham-erdington",
    65597 => "birmingham-hall-green",
    66072 => "birmingham-hodge-hill",
    65989 => "birmingham-ladywood",
    65966 => "birmingham-northfield",
    66028 => "birmingham-perry-barr",
    65804 => "birmingham-selly-oak",
    65707 => "birmingham-yardley",
    65820 => "bishop-auckland",
    65981 => "blackburn",
    65583 => "blackley-and-broughton",
    65750 => "blackpool-n-and-cleveleys",
    65679 => "blackpool-south",
    66093 => "blaenau-gwent",
    65805 => "blaydon",
    65753 => "blyth-valley",
    65841 => "bognor-regis-and-littleha",
    65628 => "bolsover",
    65646 => "bolton-north-east",
    65712 => "bolton-south-east",
    65738 => "bolton-west",
    65821 => "bootle",
    65969 => "boston-and-skegness",
    66071 => "bosworth",
    65993 => "bournemouth-east",
    65933 => "bournemouth-west",
    65697 => "bracknell",
    65694 => "bradford-east",
    65995 => "bradford-s",
    66036 => "bradford-w",
    65670 => "braintree",
    66088 => "brecon-and-radnorshire",
    66065 => "brent-central",
    65595 => "brent-n",
    65958 => "brentford-and-isleworth",
    65685 => "brentwood-and-ongar",
    66095 => "bridgend",
    65620 => "bridgwater-and-w-somerset",
    66000 => "brigg-and-goole",
    65844 => "brighton-kemptown",
    65787 => "brighton-pavilion",
    65839 => "bristol-e",
    66009 => "bristol-n-w",
    66031 => "bristol-s",
    65574 => "bristol-w",
    65852 => "broadland",
    65954 => "bromley-and-chislehurst",
    65617 => "bromsgrove",
    65639 => "broxbourne",
    65849 => "broxtowe",
    65909 => "buckingham",
    65846 => "burnley",
    65708 => "burton",
    66015 => "bury-n",
    65975 => "bury-s",
    66035 => "bury-st-edmunds",
    66106 => "caerphilly",
    14406 => "caithness-sutherland-and",
    65906 => "calder-valley",
    65913 => "camberwell-and-peckham",
    65826 => "camborne-and-redruth",
    65927 => "cambridge",
    65790 => "cannock-chase",
    65878 => "canterbury",
    66090 => "cardiff-central",
    66120 => "cardiff-n",
    66119 => "cardiff-s-and-penarth",
    66114 => "cardiff-w",
    65929 => "carlisle",
    66089 => "carmarthen-e-and-dinefwr",
    66109 => "carmarthen-w-and-s-pembro",
    65972 => "carshalton-and-wallington",
    65914 => "castle-point",
    14407 => "central-ayrshire",
    65749 => "central-devon",
    65748 => "central-suffolk-and-n-ips",
    66110 => "ceredigion",
    65615 => "charnwood",
    66075 => "chatham-and-aylesford",
    65727 => "cheadle",
    65797 => "chelmsford",
    65818 => "chelsea-and-fulham",
    65946 => "cheltenham",
    65801 => "chesham-and-amersham",
    65980 => "chesterfield",
    65558 => "chichester",
    65721 => "chingford-and-woodford-gr",
    65940 => "chippenham",
    65886 => "chipping-barnet",
    65792 => "chorley",
    65885 => "christchurch",
    65759 => "cities-of-london-and-west",
    65734 => "city-of-chester",
    66021 => "city-of-durham",
    66030 => "clacton",
    66057 => "cleethorpes",
    66121 => "clwyd-s",
    66100 => "clwyd-w",
    14408 => "coatbridge-chryston-and-b",
    65926 => "colchester",
    65835 => "colne-valley",
    65771 => "congleton",
    65893 => "copeland",
    65590 => "corby",
    65636 => "coventry-n-e",
    65575 => "coventry-n-w",
    65877 => "coventry-s",
    65781 => "crawley",
    65572 => "crewe-and-nantwich",
    65603 => "croydon-central",
    65867 => "croydon-n",
    65923 => "croydon-s",
    14409 => "cumbernauld-kilsyth-and-k",
    66105 => "cynon-valley",
    65985 => "dagenham-and-rainham",
    65802 => "darlington",
    66011 => "dartford",
    66025 => "daventry",
    66112 => "delyn",
    65924 => "denton-and-reddish",
    66070 => "derby-n",
    65863 => "derby-s",
    65799 => "derbyshire-dales",
    65723 => "devizes",
    65746 => "dewsbury",
    65553 => "don-valley",
    65621 => "doncaster-central",
    65672 => "doncaster-n",
    65555 => "dover",
    65806 => "dudley-n",
    66054 => "dudley-s",
    65808 => "dulwich-and-w-norwood",
    14410 => "dumfries-and-galloway",
    14411 => "dumfriesshire-clydesdale",
    14412 => "dundee-e",
    14413 => "dundee-w",
    14414 => "dunfermline-and-w-fife",
    66096 => "dwyfor-meirionnydd",
    66128 => "e-antrim",
    65813 => "e-devon",
    14415 => "e-dunbartonshire",
    65573 => "e-ham",
    65569 => "e-hampshire",
    14416 => "e-kilbride-strathaven-and",
    66129 => "e-londonderry",
    14417 => "e-lothian",
    14418 => "e-renfrewshire",
    65856 => "e-surrey",
    65780 => "e-worthing-and-shoreham",
    65979 => "e-yorkshire",
    65755 => "ealing-central-and-acton",
    65701 => "ealing-n",
    65794 => "ealing-southall",
    65823 => "easington",
    65714 => "eastbourne",
    65881 => "eastleigh",
    65756 => "eddisbury",
    14419 => "edinburgh-e",
    14420 => "edinburgh-n-and-leith",
    14422 => "edinburgh-s-w",
    14421 => "edinburgh-s",
    14423 => "edinburgh-w",
    65570 => "edmonton",
    65991 => "ellesmere-port-and-neston",
    65677 => "elmet-and-rothwell",
    65816 => "eltham",
    66050 => "enfield-n",
    65567 => "enfield-southgate",
    66044 => "epping-forest",
    65803 => "epsom-and-ewell",
    65743 => "erewash",
    66023 => "erith-and-thamesmead",
    66062 => "esher-and-walton",
    66033 => "exeter",
    14424 => "falkirk",
    65857 => "fareham",
    65764 => "faversham-and-mid-kent",
    65655 => "feltham-and-heston",
    66130 => "fermanagh-and-s-tyrone",
    65865 => "filton-and-bradley-stoke",
    65938 => "finchley-and-golders-gree",
    65779 => "folkestone-and-hythe",
    66064 => "forest-of-dean",
    66131 => "foyle",
    65955 => "fylde",
    65952 => "gainsborough",
    65900 => "garston-and-halewood",
    65870 => "gateshead",
    65551 => "gedling",
    65864 => "gillingham-and-rainham",
    14425 => "glasgow-central",
    14426 => "glasgow-e",
    14428 => "glasgow-n-e",
    14429 => "glasgow-n-w",
    14427 => "glasgow-n",
    14431 => "glasgow-s-w",
    14430 => "glasgow-s",
    14432 => "glenrothes",
    65996 => "gloucester",
    14433 => "gordon",
    65928 => "gosport",
    66083 => "gower",
    65683 => "grantham-and-stamford",
    65944 => "gravesham",
    65600 => "great-grimsby",
    65627 => "great-yarmouth",
    65837 => "greenwich-and-woolwich",
    65838 => "guildford",
    65550 => "hackney-n-and-stoke-newin",
    65752 => "hackney-s-and-shoreditch",
    65971 => "halesowen-and-rowley-regi",
    65599 => "halifax",
    65671 => "haltemprice-and-howden",
    65915 => "halton",
    65836 => "hammersmith",
    65576 => "hampstead-and-kilburn",
    65675 => "harborough",
    65875 => "harlow",
    65578 => "harrogate-and-knaresborou",
    65650 => "harrow-e",
    65796 => "harrow-w",
    65990 => "hartlepool",
    65674 => "harwich-and-n-essex",
    65640 => "hastings-and-rye",
    65699 => "havant",
    65912 => "hayes-and-harlington",
    65557 => "hazel-grove",
    65967 => "hemel-hempstead",
    66018 => "hemsworth",
    65754 => "hendon",
    65786 => "henley",
    65582 => "hereford-and-s-herefordsh",
    66003 => "hertford-and-stortford",
    65994 => "hertsmere",
    65850 => "hexham",
    65814 => "heywood-and-middleton",
    66052 => "high-peak",
    65724 => "hitchin-and-harpenden",
    65824 => "holborn-and-st-pancras",
    66069 => "hornchurch-and-upminster",
    65883 => "hornsey-and-wood-green",
    65717 => "horsham",
    65947 => "houghton-and-sunderland-s",
    65691 => "hove",
    65624 => "huddersfield",
    65592 => "huntingdon",
    65899 => "hyndburn",
    65630 => "ilford-n",
    65585 => "ilford-s",
    14434 => "inverclyde",
    14435 => "inverness-nairn-badenoch",
    65925 => "ipswich",
    65791 => "isle-of-wight",
    65937 => "islington-n",
    65882 => "islington-s-and-finsbury",
    66097 => "islwyn",
    66026 => "jarrow",
    65871 => "keighley",
    65968 => "kenilworth-and-southam",
    65939 => "kensington",
    66001 => "kettering",
    14436 => "kilmarnock-and-loudoun",
    65778 => "kingston-and-surbiton",
    65709 => "kingston-upon-hull-e",
    65618 => "kingston-upon-hull-n",
    65984 => "kingston-upon-hull-w-and",
    66053 => "kingswood",
    14437 => "kirkcaldy-and-cowdenbeath",
    65869 => "knowsley",
    66132 => "lagan-valley",
    14438 => "lanark-and-hamilton-e",
    65568 => "lancaster-and-fleetwood",
    65765 => "leeds-central",
    65941 => "leeds-e",
    65866 => "leeds-n-e",
    66068 => "leeds-n-w",
    65988 => "leeds-w",
    65807 => "leicester-e",
    65604 => "leicester-s",
    65587 => "leicester-w",
    65978 => "leigh",
    66020 => "lewes",
    66041 => "lewisham-deptford",
    65705 => "lewisham-e",
    65616 => "lewisham-w-and-penge",
    66013 => "leyton-and-wanstead",
    66046 => "lichfield",
    65704 => "lincoln",
    14439 => "linlithgow-and-e-falkirk",
    66066 => "liverpool-riverside",
    65766 => "liverpool-w-derby",
    65970 => "liverpool-walton",
    65644 => "liverpool-wavertree",
    14440 => "livingston",
    66117 => "llanelli",
    65785 => "loughborough",
    65987 => "louth-and-horncastle",
    65690 => "ludlow",
    65887 => "luton-n",
    66080 => "luton-s",
    65896 => "macclesfield",
    65901 => "maidenhead",
    65936 => "maidstone-and-the-weald",
    65645 => "makerfield",
    65661 => "maldon",
    66048 => "manchester-central",
    65834 => "manchester-gorton",
    65819 => "manchester-withington",
    65647 => "mansfield",
    65772 => "meon-valley",
    65932 => "meriden",
    66086 => "merthyr-tydfil-and-rhymne",
    65718 => "mid-bedfordshire",
    66007 => "mid-derbyshire",
    66061 => "mid-dorset-and-n-poole",
    65949 => "mid-norfolk",
    65999 => "mid-sussex",
    66133 => "mid-ulster",
    65888 => "mid-worcestershire",
    65657 => "middlesbrough-s-and-e-cle",
    65998 => "middlesbrough",
    14441 => "midlothian",
    65953 => "milton-keynes-n",
    66076 => "milton-keynes-s",
    66038 => "mitcham-and-morden",
    65693 => "mole-valley",
    66084 => "monmouth",
    66111 => "montgomeryshire",
    14442 => "moray",
    65633 => "morecambe-and-lunesdale",
    65735 => "morley-and-outwood",
    14443 => "motherwell-and-wishaw",
    66135 => "n-antrim",
    14445 => "n-ayrshire-and-arran",
    65602 => "n-cornwall",
    65658 => "n-devon",
    65702 => "n-dorset",
    66136 => "n-down",
    65745 => "n-durham",
    65855 => "n-e-bedfordshire",
    66063 => "n-e-cambridgeshire",
    65676 => "n-e-derbyshire",
    14446 => "n-e-fife",
    65729 => "n-e-hampshire",
    65840 => "n-e-hertfordshire",
    65619 => "n-e-somerset",
    65642 => "n-herefordshire",
    65872 => "n-norfolk",
    66017 => "n-shropshire",
    65817 => "n-somerset",
    65760 => "n-swindon",
    65605 => "n-thanet",
    65720 => "n-tyneside",
    65565 => "n-w-cambridgeshire",
    65859 => "n-w-durham",
    65894 => "n-w-hampshire",
    65776 => "n-w-leicestershire",
    65713 => "n-w-norfolk",
    66024 => "n-warwickshire",
    65822 => "n-wiltshire",
    14444 => "na-h-eileanan-an-iar",
    66082 => "neath",
    65556 => "new-forest-e",
    65815 => "new-forest-w",
    65696 => "newark",
    65862 => "newbury",
    65861 => "newcastle-under-lyme",
    66055 => "newcastle-upon-tyne-centr",
    65594 => "newcastle-upon-tyne-e",
    65664 => "newcastle-upon-tyne-n",
    66094 => "newport-e",
    66099 => "newport-w",
    66134 => "newry-and-armagh",
    65828 => "newton-abbot",
    65918 => "normanton-pontefract-and",
    66059 => "northampton-n",
    65910 => "northampton-s",
    65768 => "norwich-n",
    65634 => "norwich-s",
    65559 => "nottingham-e",
    65643 => "nottingham-n",
    65945 => "nottingham-s",
    65663 => "nuneaton",
    14447 => "ochil-and-s-perthshire",
    66107 => "ogmore",
    65653 => "old-bexley-and-sidcup",
    65903 => "oldham-e-and-saddleworth",
    66022 => "oldham-w-and-royton",
    14448 => "orkney-and-shetland",
    65682 => "orpington",
    66060 => "oxford-e",
    65564 => "oxford-w-and-abingdon",
    14449 => "paisley-and-renfrew-n",
    14450 => "paisley-and-renfrew-s",
    65668 => "pendle",
    66002 => "penistone-and-stocksbridg",
    66081 => "penrith-and-the-border",
    14451 => "perth-and-n-perthshire",
    65649 => "peterborough",
    65974 => "plymouth-moor-view",
    65737 => "plymouth-sutton-and-devon",
    66087 => "pontypridd",
    65860 => "poole",
    65917 => "poplar-and-limehouse",
    65566 => "portsmouth-n",
    66014 => "portsmouth-s",
    66102 => "preseli-pembrokeshire",
    65673 => "preston",
    65637 => "pudsey",
    66045 => "putney",
    65795 => "rayleigh-and-wickford",
    65973 => "reading-e",
    65982 => "reading-w",
    66032 => "redcar",
    65700 => "redditch",
    66005 => "reigate",
    66092 => "rhondda",
    65579 => "ribble-valley",
    65598 => "richmond-park",
    65722 => "richmond-yorks",
    65843 => "rochdale",
    66043 => "rochester-and-strood",
    65584 => "rochford-and-southend-e",
    66077 => "romford",
    65884 => "romsey-and-southampton-n",
    14452 => "ross-skye-and-lochaber",
    66019 => "rossendale-and-darwen",
    65930 => "rother-valley",
    66029 => "rotherham",
    65656 => "rugby",
    65681 => "ruislip-northwood-and-pin",
    65589 => "runnymede-and-weybridge",
    65736 => "rushcliffe",
    14453 => "rutherglen-and-hamilton-w",
    65833 => "rutland-and-melton",
    66137 => "s-antrim",
    65962 => "s-basildon-and-e-thurrock",
    65922 => "s-cambridgeshire",
    65762 => "s-derbyshire",
    65788 => "s-dorset",
    66138 => "s-down",
    65997 => "s-e-cambridgeshire",
    65684 => "s-e-cornwall",
    66051 => "s-holland-and-the-deeping",
    66034 => "s-leicestershire",
    65666 => "s-norfolk",
    65902 => "s-northamptonshire",
    65951 => "s-ribble",
    65719 => "s-shields",
    65943 => "s-staffordshire",
    65614 => "s-suffolk",
    65800 => "s-swindon",
    65829 => "s-thanet",
    65848 => "s-w-bedfordshire",
    65775 => "s-w-devon",
    65596 => "s-w-hertfordshire",
    65652 => "s-w-norfolk",
    65678 => "s-w-surrey",
    65956 => "s-w-wiltshire",
    65654 => "saffron-walden",
    65688 => "salford-and-eccles",
    65889 => "salisbury",
    65891 => "scarborough-and-whitby",
    66027 => "scunthorpe",
    65763 => "sedgefield",
    65706 => "sefton-central",
    65842 => "selby-and-ainsty",
    65698 => "sevenoaks",
    65601 => "sheffield-brightside-and",
    65957 => "sheffield-central",
    65741 => "sheffield-hallam",
    65549 => "sheffield-heeley",
    65793 => "sheffield-s-e",
    65632 => "sherwood",
    65959 => "shipley",
    65563 => "shrewsbury-and-atcham",
    65610 => "sittingbourne-and-sheppey",
    65986 => "skipton-and-ripon",
    65920 => "sleaford-and-n-hykeham",
    65680 => "slough",
    65879 => "solihull",
    65812 => "somerton-and-frome",
    66016 => "southampton-itchen",
    65580 => "southampton-test",
    65876 => "southend-w",
    65728 => "southport",
    65942 => "spelthorne",
    65715 => "st-albans",
    65591 => "st-austell-and-newquay",
    66073 => "st-helens-n",
    65732 => "st-helens-s-and-whiston",
    65854 => "st-ives",
    66067 => "stafford",
    65907 => "staffordshire-moorlands",
    65960 => "stalybridge-and-hyde",
    65571 => "stevenage",
    14454 => "stirling",
    65606 => "stockport",
    65641 => "stockton-n",
    65908 => "stockton-s",
    65710 => "stoke-on-trent-central",
    65783 => "stoke-on-trent-n",
    65770 => "stoke-on-trent-s",
    65950 => "stone",
    65609 => "stourbridge",
    66139 => "strangford",
    65648 => "stratford-on-avon",
    66042 => "streatham",
    65911 => "stretford-and-urmston",
    65858 => "stroud",
    65607 => "suffolk-coastal",
    65586 => "sunderland-central",
    65747 => "surrey-heath",
    66040 => "sutton-and-cheam",
    65703 => "sutton-coldfield",
    66091 => "swansea-e",
    66118 => "swansea-w",
    65880 => "tamworth",
    65964 => "tatton",
    65767 => "taunton-deane",
    65992 => "telford",
    65976 => "tewkesbury",
    65789 => "the-cotswolds",
    65977 => "the-wrekin",
    65686 => "thirsk-and-malton",
    65905 => "thornbury-and-yate",
    65919 => "thurrock",
    65761 => "tiverton-and-honiton",
    65744 => "tonbridge-and-malling",
    65554 => "tooting",
    65692 => "torbay",
    66104 => "torfaen",
    65904 => "torridge-and-w-devon",
    65810 => "totnes",
    66074 => "tottenham",
    65659 => "truro-and-falmouth",
    65660 => "tunbridge-wells",
    65782 => "twickenham",
    65868 => "tynemouth",
    66140 => "upper-bann",
    65613 => "uxbridge-and-s-ruislip",
    66116 => "vale-of-clwyd",
    66098 => "vale-of-glamorgan",
    65825 => "vauxhall",
    14455 => "w-aberdeenshire-and-kinca",
    65983 => "w-bromwich-e",
    66047 => "w-bromwich-west",
    65716 => "w-dorset",
    14456 => "w-dunbartonshire",
    66058 => "w-ham",
    65873 => "w-lancashire",
    65629 => "w-suffolk",
    66141 => "w-tyrone",
    65758 => "w-worcestershire",
    65733 => "wakefield",
    65635 => "wallasey",
    65890 => "walsall-n",
    65832 => "walsall-s",
    65651 => "walthamstow",
    65631 => "wansbeck",
    65638 => "wantage",
    66079 => "warley",
    65874 => "warrington-n",
    65916 => "warrington-s",
    65608 => "warwick-and-leamington",
    66049 => "washington-and-sunderland",
    65626 => "watford",
    66004 => "waveney",
    65961 => "wealden",
    65769 => "weaver-vale",
    65830 => "wellingborough",
    65560 => "wells",
    65740 => "welwyn-hatfield",
    65588 => "wentworth-and-dearne",
    65851 => "westminster-n",
    65963 => "westmorland-and-lonsdale",
    65742 => "weston-super-mare",
    65612 => "wigan",
    65827 => "wimbledon",
    65921 => "winchester",
    65552 => "windsor",
    65847 => "wirral-s",
    65897 => "wirral-w",
    65831 => "witham",
    65622 => "witney",
    66039 => "woking",
    65774 => "wokingham",
    65777 => "wolverhampton-n-e",
    65593 => "wolverhampton-s-e",
    65948 => "wolverhampton-s-w",
    65577 => "worcester",
    65625 => "workington",
    65757 => "worsley-and-eccles-s",
    65562 => "worthing-w",
    66113 => "wrexham",
    66010 => "wycombe",
    65695 => "wyre-and-preston-n",
    66078 => "wyre-forest",
    65669 => "wythenshawe-and-sale-e",
    65935 => "yeovil",
    66115 => "ynys-mon",
    65965 => "york-central",
    66037 => "york-outer"
  }

  CONSTITUENCY_LIST = [
    [ "Aberavon","aberavon","66101" ],
    [ "Aberconwy","aberconwy","66085" ],
    [ "Aberdeen North","aberdeen-north","14398" ],
    [ "Aberdeen South","aberdeen-south","14399" ],
    [ "Airdrie and Shotts","airdrie-and-shotts","14400" ],
    [ "Aldershot","aldershot","65730" ],
    [ "Aldridge-Brownhills","aldridge-brownhills","65773" ],
    [ "Altrincham and Sale West","altrincham-and-sale-west","65892" ],
    [ "Alyn and Deeside","alyn-and-deeside","66103" ],
    [ "Amber Valley","amber-valley","65809" ],
    [ "Angus","angus","14401" ],
    [ "Arfon","arfon","66108" ],
    [ "Argyll and Bute","argyll-and-bute","14402" ],
    [ "Arundel and South Downs","arundel-and-south-downs","65784" ],
    [ "Ashfield","ashfield","65895" ],
    [ "Ashford","ashford","65811" ],
    [ "Ashton-under-Lyne","ashton-under-lyne","66056" ],
    [ "Aylesbury","aylesbury","65739" ],
    [ "Ayr, Carrick and Cumnock","ayr-carrick-and-cumnock","14403" ],
    [ "Banbury","banbury","66008" ],
    [ "Banff and Buchan","banff-and-buchan","14404" ],
    [ "Barking","barking","65662" ],
    [ "Barnsley Central","barnsley-central","65665" ],
    [ "Barnsley East","barnsley-east","66012" ],
    [ "Barrow and Furness","barrow-and-furness","66006" ],
    [ "Basildon and Billericay","basildon-and-billericay","65898" ],
    [ "Basingstoke","basingstoke","65623" ],
    [ "Bassetlaw","bassetlaw","65711" ],
    [ "Bath","bath","65798" ],
    [ "Batley and Spen","batley-and-spen","65751" ],
    [ "Battersea","battersea","65731" ],
    [ "Beaconsfield","beaconsfield","65687" ],
    [ "Beckenham","beckenham","65725" ],
    [ "Bedford","bedford","65561" ],
    [ "Belfast East","belfast-east","66124" ],
    [ "Belfast North","belfast-north","66125" ],
    [ "Belfast South","belfast-south","66126" ],
    [ "Belfast West","belfast-west","66127" ],
    [ "Bermondsey and Old Southwark","bermondsey-and-old-southw","65689" ],
    [ "Berwick-upon-Tweed","berwick-upon-tweed","65726" ],
    [ "Berwickshire, Roxburgh and Selkirk","berwickshire-roxburgh-and","14405" ],
    [ "Bethnal Green and Bow","bethnal-green-and-bow","65853" ],
    [ "Beverley and Holderness","beverley-and-holderness","65934" ],
    [ "Bexhill and Battle","bexhill-and-battle","65845" ],
    [ "Bexleyheath and Crayford","bexleyheath-and-crayford","65611" ],
    [ "Birkenhead","birkenhead","65581" ],
    [ "Birmingham, Edgbaston","birmingham-edgbaston","65931" ],
    [ "Birmingham, Erdington","birmingham-erdington","65667" ],
    [ "Birmingham, Hall Green","birmingham-hall-green","65597" ],
    [ "Birmingham, Hodge Hill","birmingham-hodge-hill","66072" ],
    [ "Birmingham, Ladywood","birmingham-ladywood","65989" ],
    [ "Birmingham, Northfield","birmingham-northfield","65966" ],
    [ "Birmingham, Perry Barr","birmingham-perry-barr","66028" ],
    [ "Birmingham, Selly Oak","birmingham-selly-oak","65804" ],
    [ "Birmingham, Yardley","birmingham-yardley","65707" ],
    [ "Bishop Auckland","bishop-auckland","65820" ],
    [ "Blackburn","blackburn","65981" ],
    [ "Blackley and Broughton","blackley-and-broughton","65583" ],
    [ "Blackpool North and Cleveleys","blackpool-n-and-cleveleys","65750" ],
    [ "Blackpool South","blackpool-south","65679" ],
    [ "Blaenau Gwent","blaenau-gwent","66093" ],
    [ "Blaydon","blaydon","65805" ],
    [ "Blyth Valley","blyth-valley","65753" ],
    [ "Bognor Regis and Littlehampton","bognor-regis-and-littleha","65841" ],
    [ "Bolsover","bolsover","65628" ],
    [ "Bolton North East","bolton-north-east","65646" ],
    [ "Bolton South East","bolton-south-east","65712" ],
    [ "Bolton West","bolton-west","65738" ],
    [ "Bootle","bootle","65821" ],
    [ "Boston and Skegness","boston-and-skegness","65969" ],
    [ "Bosworth","bosworth","66071" ],
    [ "Bournemouth East","bournemouth-east","65993" ],
    [ "Bournemouth West","bournemouth-west","65933" ],
    [ "Bracknell","bracknell","65697" ],
    [ "Bradford East","bradford-east","65694" ],
    [ "Bradford South","bradford-s","65995" ],
    [ "Bradford West","bradford-w","66036" ],
    [ "Braintree","braintree","65670" ],
    [ "Brecon and Radnorshire","brecon-and-radnorshire","66088" ],
    [ "Brent Central","brent-central","66065" ],
    [ "Brent North","brent-n","65595" ],
    [ "Brentford and Isleworth","brentford-and-isleworth","65958" ],
    [ "Brentwood and Ongar","brentwood-and-ongar","65685" ],
    [ "Bridgend","bridgend","66095" ],
    [ "Bridgwater and West Somerset","bridgwater-and-w-somerset","65620" ],
    [ "Brigg and Goole","brigg-and-goole","66000" ],
    [ "Brighton, Kemptown","brighton-kemptown","65844" ],
    [ "Brighton, Pavilion","brighton-pavilion","65787" ],
    [ "Bristol East","bristol-e","65839" ],
    [ "Bristol North West","bristol-n-w","66009" ],
    [ "Bristol South","bristol-s","66031" ],
    [ "Bristol West","bristol-w","65574" ],
    [ "Broadland","broadland","65852" ],
    [ "Bromley and Chislehurst","bromley-and-chislehurst","65954" ],
    [ "Bromsgrove","bromsgrove","65617" ],
    [ "Broxbourne","broxbourne","65639" ],
    [ "Broxtowe","broxtowe","65849" ],
    [ "Buckingham","buckingham","65909" ],
    [ "Burnley","burnley","65846" ],
    [ "Burton","burton","65708" ],
    [ "Bury North","bury-n","66015" ],
    [ "Bury South","bury-s","65975" ],
    [ "Bury St Edmunds","bury-st-edmunds","66035" ],
    [ "Caerphilly","caerphilly","66106" ],
    [ "Caithness, Sutherland and Easter Ross","caithness-sutherland-and","14406" ],
    [ "Calder Valley","calder-valley","65906" ],
    [ "Camberwell and Peckham","camberwell-and-peckham","65913" ],
    [ "Camborne and Redruth","camborne-and-redruth","65826" ],
    [ "Cambridge","cambridge","65927" ],
    [ "Cannock Chase","cannock-chase","65790" ],
    [ "Canterbury","canterbury","65878" ],
    [ "Cardiff Central","cardiff-central","66090" ],
    [ "Cardiff North","cardiff-n","66120" ],
    [ "Cardiff South and Penarth","cardiff-s-and-penarth","66119" ],
    [ "Cardiff West","cardiff-w","66114" ],
    [ "Carlisle","carlisle","65929" ],
    [ "Carmarthen East and Dinefwr","carmarthen-e-and-dinefwr","66089" ],
    [ "Carmarthen West and South Pembrokeshire","carmarthen-w-and-s-pembro","66109" ],
    [ "Carshalton and Wallington","carshalton-and-wallington","65972" ],
    [ "Castle Point","castle-point","65914" ],
    [ "Central Ayrshire","central-ayrshire","14407" ],
    [ "Central Devon","central-devon","65749" ],
    [ "Central Suffolk and North Ipswich","central-suffolk-and-n-ips","65748" ],
    [ "Ceredigion","ceredigion","66110" ],
    [ "Charnwood","charnwood","65615" ],
    [ "Chatham and Aylesford","chatham-and-aylesford","66075" ],
    [ "Cheadle","cheadle","65727" ],
    [ "Chelmsford","chelmsford","65797" ],
    [ "Chelsea and Fulham","chelsea-and-fulham","65818" ],
    [ "Cheltenham","cheltenham","65946" ],
    [ "Chesham and Amersham","chesham-and-amersham","65801" ],
    [ "Chesterfield","chesterfield","65980" ],
    [ "Chichester","chichester","65558" ],
    [ "Chingford and Woodford Green","chingford-and-woodford-gr","65721" ],
    [ "Chippenham","chippenham","65940" ],
    [ "Chipping Barnet","chipping-barnet","65886" ],
    [ "Chorley","chorley","65792" ],
    [ "Christchurch","christchurch","65885" ],
    [ "Cities of London and Westminster","cities-of-london-and-west","65759" ],
    [ "City of Chester","city-of-chester","65734" ],
    [ "City of Durham","city-of-durham","66021" ],
    [ "Clacton","clacton","66030" ],
    [ "Cleethorpes","cleethorpes","66057" ],
    [ "Clwyd South","clwyd-s","66121" ],
    [ "Clwyd West","clwyd-w","66100" ],
    [ "Coatbridge, Chryston and Bellshill","coatbridge-chryston-and-b","14408" ],
    [ "Colchester","colchester","65926" ],
    [ "Colne Valley","colne-valley","65835" ],
    [ "Congleton","congleton","65771" ],
    [ "Copeland","copeland","65893" ],
    [ "Corby","corby","65590" ],
    [ "Coventry North East","coventry-n-e","65636" ],
    [ "Coventry North West","coventry-n-w","65575" ],
    [ "Coventry South","coventry-s","65877" ],
    [ "Crawley","crawley","65781" ],
    [ "Crewe and Nantwich","crewe-and-nantwich","65572" ],
    [ "Croydon Central","croydon-central","65603" ],
    [ "Croydon North","croydon-n","65867" ],
    [ "Croydon South","croydon-s","65923" ],
    [ "Cumbernauld, Kilsyth and Kirkintilloch East","cumbernauld-kilsyth-and-k","14409" ],
    [ "Cynon Valley","cynon-valley","66105" ],
    [ "Dagenham and Rainham","dagenham-and-rainham","65985" ],
    [ "Darlington","darlington","65802" ],
    [ "Dartford","dartford","66011" ],
    [ "Daventry","daventry","66025" ],
    [ "Delyn","delyn","66112" ],
    [ "Denton and Reddish","denton-and-reddish","65924" ],
    [ "Derby North","derby-n","66070" ],
    [ "Derby South","derby-s","65863" ],
    [ "Derbyshire Dales","derbyshire-dales","65799" ],
    [ "Devizes","devizes","65723" ],
    [ "Dewsbury","dewsbury","65746" ],
    [ "Don Valley","don-valley","65553" ],
    [ "Doncaster Central","doncaster-central","65621" ],
    [ "Doncaster North","doncaster-n","65672" ],
    [ "Dover","dover","65555" ],
    [ "Dudley North","dudley-n","65806" ],
    [ "Dudley South","dudley-s","66054" ],
    [ "Dulwich and West Norwood","dulwich-and-w-norwood","65808" ],
    [ "Dumfries and Galloway","dumfries-and-galloway","14410" ],
    [ "Dumfriesshire, Clydesdale and Tweeddale","dumfriesshire-clydesdale","14411" ],
    [ "Dundee East","dundee-e","14412" ],
    [ "Dundee West","dundee-w","14413" ],
    [ "Dunfermline and West Fife","dunfermline-and-w-fife","14414" ],
    [ "Dwyfor Meirionnydd","dwyfor-meirionnydd","66096" ],
    [ "East Antrim","e-antrim","66128" ],
    [ "East Devon","e-devon","65813" ],
    [ "East Dunbartonshire","e-dunbartonshire","14415" ],
    [ "East Ham","e-ham","65573" ],
    [ "East Hampshire","e-hampshire","65569" ],
    [ "East Kilbride, Strathaven and Lesmahagow","e-kilbride-strathaven-and","14416" ],
    [ "East Londonderry","e-londonderry","66129" ],
    [ "East Lothian","e-lothian","14417" ],
    [ "East Renfrewshire","e-renfrewshire","14418" ],
    [ "East Surrey","e-surrey","65856" ],
    [ "East Worthing and Shoreham","e-worthing-and-shoreham","65780" ],
    [ "East Yorkshire","e-yorkshire","65979" ],
    [ "Ealing Central and Acton","ealing-central-and-acton","65755" ],
    [ "Ealing North","ealing-n","65701" ],
    [ "Ealing, Southall","ealing-southall","65794" ],
    [ "Easington","easington","65823" ],
    [ "Eastbourne","eastbourne","65714" ],
    [ "Eastleigh","eastleigh","65881" ],
    [ "Eddisbury","eddisbury","65756" ],
    [ "Edinburgh East","edinburgh-e","14419" ],
    [ "Edinburgh North and Leith","edinburgh-n-and-leith","14420" ],
    [ "Edinburgh South West","edinburgh-s-w","14422" ],
    [ "Edinburgh South","edinburgh-s","14421" ],
    [ "Edinburgh West","edinburgh-w","14423" ],
    [ "Edmonton","edmonton","65570" ],
    [ "Ellesmere Port and Neston","ellesmere-port-and-neston","65991" ],
    [ "Elmet and Rothwell","elmet-and-rothwell","65677" ],
    [ "Eltham","eltham","65816" ],
    [ "Enfield North","enfield-n","66050" ],
    [ "Enfield, Southgate","enfield-southgate","65567" ],
    [ "Epping Forest","epping-forest","66044" ],
    [ "Epsom and Ewell","epsom-and-ewell","65803" ],
    [ "Erewash","erewash","65743" ],
    [ "Erith and Thamesmead","erith-and-thamesmead","66023" ],
    [ "Esher and Walton","esher-and-walton","66062" ],
    [ "Exeter","exeter","66033" ],
    [ "Falkirk","falkirk","14424" ],
    [ "Fareham","fareham","65857" ],
    [ "Faversham and Mid Kent","faversham-and-mid-kent","65764" ],
    [ "Feltham and Heston","feltham-and-heston","65655" ],
    [ "Fermanagh and South Tyrone","fermanagh-and-s-tyrone","66130" ],
    [ "Filton and Bradley Stoke","filton-and-bradley-stoke","65865" ],
    [ "Finchley and Golders Green","finchley-and-golders-gree","65938" ],
    [ "Folkestone and Hythe","folkestone-and-hythe","65779" ],
    [ "Forest of Dean","forest-of-dean","66064" ],
    [ "Foyle","foyle","66131" ],
    [ "Fylde","fylde","65955" ],
    [ "Gainsborough","gainsborough","65952" ],
    [ "Garston and Halewood","garston-and-halewood","65900" ],
    [ "Gateshead","gateshead","65870" ],
    [ "Gedling","gedling","65551" ],
    [ "Gillingham and Rainham","gillingham-and-rainham","65864" ],
    [ "Glasgow Central","glasgow-central","14425" ],
    [ "Glasgow East","glasgow-e","14426" ],
    [ "Glasgow North East","glasgow-n-e","14428" ],
    [ "Glasgow North West","glasgow-n-w","14429" ],
    [ "Glasgow North","glasgow-n","14427" ],
    [ "Glasgow South West","glasgow-s-w","14431" ],
    [ "Glasgow South","glasgow-s","14430" ],
    [ "Glenrothes","glenrothes","14432" ],
    [ "Gloucester","gloucester","65996" ],
    [ "Gordon","gordon","14433" ],
    [ "Gosport","gosport","65928" ],
    [ "Gower","gower","66083" ],
    [ "Grantham and Stamford","grantham-and-stamford","65683" ],
    [ "Gravesham","gravesham","65944" ],
    [ "Great Grimsby","great-grimsby","65600" ],
    [ "Great Yarmouth","great-yarmouth","65627" ],
    [ "Greenwich and Woolwich","greenwich-and-woolwich","65837" ],
    [ "Guildford","guildford","65838" ],
    [ "Hackney North and Stoke Newington","hackney-n-and-stoke-newin","65550" ],
    [ "Hackney South and Shoreditch","hackney-s-and-shoreditch","65752" ],
    [ "Halesowen and Rowley Regis","halesowen-and-rowley-regi","65971" ],
    [ "Halifax","halifax","65599" ],
    [ "Haltemprice and Howden","haltemprice-and-howden","65671" ],
    [ "Halton","halton","65915" ],
    [ "Hammersmith","hammersmith","65836" ],
    [ "Hampstead and Kilburn","hampstead-and-kilburn","65576" ],
    [ "Harborough","harborough","65675" ],
    [ "Harlow","harlow","65875" ],
    [ "Harrogate and Knaresborough","harrogate-and-knaresborou","65578" ],
    [ "Harrow East","harrow-e","65650" ],
    [ "Harrow West","harrow-w","65796" ],
    [ "Hartlepool","hartlepool","65990" ],
    [ "Harwich and North Essex","harwich-and-n-essex","65674" ],
    [ "Hastings and Rye","hastings-and-rye","65640" ],
    [ "Havant","havant","65699" ],
    [ "Hayes and Harlington","hayes-and-harlington","65912" ],
    [ "Hazel Grove","hazel-grove","65557" ],
    [ "Hemel Hempstead","hemel-hempstead","65967" ],
    [ "Hemsworth","hemsworth","66018" ],
    [ "Hendon","hendon","65754" ],
    [ "Henley","henley","65786" ],
    [ "Hereford and South Herefordshire","hereford-and-s-herefordsh","65582" ],
    [ "Hertford and Stortford","hertford-and-stortford","66003" ],
    [ "Hertsmere","hertsmere","65994" ],
    [ "Hexham","hexham","65850" ],
    [ "Heywood and Middleton","heywood-and-middleton","65814" ],
    [ "High Peak","high-peak","66052" ],
    [ "Hitchin and Harpenden","hitchin-and-harpenden","65724" ],
    [ "Holborn and St Pancras","holborn-and-st-pancras","65824" ],
    [ "Hornchurch and Upminster","hornchurch-and-upminster","66069" ],
    [ "Hornsey and Wood Green","hornsey-and-wood-green","65883" ],
    [ "Horsham","horsham","65717" ],
    [ "Houghton and Sunderland South","houghton-and-sunderland-s","65947" ],
    [ "Hove","hove","65691" ],
    [ "Huddersfield","huddersfield","65624" ],
    [ "Huntingdon","huntingdon","65592" ],
    [ "Hyndburn","hyndburn","65899" ],
    [ "Ilford North","ilford-n","65630" ],
    [ "Ilford South","ilford-s","65585" ],
    [ "Inverclyde","inverclyde","14434" ],
    [ "Inverness, Nairn, Badenoch and Strathspey","inverness-nairn-badenoch","14435" ],
    [ "Ipswich","ipswich","65925" ],
    [ "Isle of Wight","isle-of-wight","65791" ],
    [ "Islington North","islington-n","65937" ],
    [ "Islington South and Finsbury","islington-s-and-finsbury","65882" ],
    [ "Islwyn","islwyn","66097" ],
    [ "Jarrow","jarrow","66026" ],
    [ "Keighley","keighley","65871" ],
    [ "Kenilworth and Southam","kenilworth-and-southam","65968" ],
    [ "Kensington","kensington","65939" ],
    [ "Kettering","kettering","66001" ],
    [ "Kilmarnock and Loudoun","kilmarnock-and-loudoun","14436" ],
    [ "Kingston and Surbiton","kingston-and-surbiton","65778" ],
    [ "Kingston upon Hull East","kingston-upon-hull-e","65709" ],
    [ "Kingston upon Hull North","kingston-upon-hull-n","65618" ],
    [ "Kingston upon Hull West and Hessle","kingston-upon-hull-w-and","65984" ],
    [ "Kingswood","kingswood","66053" ],
    [ "Kirkcaldy and Cowdenbeath","kirkcaldy-and-cowdenbeath","14437" ],
    [ "Knowsley","knowsley","65869" ],
    [ "Lagan Valley","lagan-valley","66132" ],
    [ "Lanark and Hamilton East","lanark-and-hamilton-e","14438" ],
    [ "Lancaster and Fleetwood","lancaster-and-fleetwood","65568" ],
    [ "Leeds Central","leeds-central","65765" ],
    [ "Leeds East","leeds-e","65941" ],
    [ "Leeds North East","leeds-n-e","65866" ],
    [ "Leeds North West","leeds-n-w","66068" ],
    [ "Leeds West","leeds-w","65988" ],
    [ "Leicester East","leicester-e","65807" ],
    [ "Leicester South","leicester-s","65604" ],
    [ "Leicester West","leicester-w","65587" ],
    [ "Leigh","leigh","65978" ],
    [ "Lewes","lewes","66020" ],
    [ "Lewisham, Deptford","lewisham-deptford","66041" ],
    [ "Lewisham East","lewisham-e","65705" ],
    [ "Lewisham West and Penge","lewisham-w-and-penge","65616" ],
    [ "Leyton and Wanstead","leyton-and-wanstead","66013" ],
    [ "Lichfield","lichfield","66046" ],
    [ "Lincoln","lincoln","65704" ],
    [ "Linlithgow and East Falkirk","linlithgow-and-e-falkirk","14439" ],
    [ "Liverpool, Riverside","liverpool-riverside","66066" ],
    [ "Liverpool, West Derby","liverpool-w-derby","65766" ],
    [ "Liverpool, Walton","liverpool-walton","65970" ],
    [ "Liverpool, Wavertree","liverpool-wavertree","65644" ],
    [ "Livingston","livingston","14440" ],
    [ "Llanelli","llanelli","66117" ],
    [ "Loughborough","loughborough","65785" ],
    [ "Louth and Horncastle","louth-and-horncastle","65987" ],
    [ "Ludlow","ludlow","65690" ],
    [ "Luton North","luton-n","65887" ],
    [ "Luton South","luton-s","66080" ],
    [ "Macclesfield","macclesfield","65896" ],
    [ "Maidenhead","maidenhead","65901" ],
    [ "Maidstone and The Weald","maidstone-and-the-weald","65936" ],
    [ "Makerfield","makerfield","65645" ],
    [ "Maldon","maldon","65661" ],
    [ "Manchester Central","manchester-central","66048" ],
    [ "Manchester, Gorton","manchester-gorton","65834" ],
    [ "Manchester, Withington","manchester-withington","65819" ],
    [ "Mansfield","mansfield","65647" ],
    [ "Meon Valley","meon-valley","65772" ],
    [ "Meriden","meriden","65932" ],
    [ "Merthyr Tydfil and Rhymney","merthyr-tydfil-and-rhymne","66086" ],
    [ "Mid Bedfordshire","mid-bedfordshire","65718" ],
    [ "Mid Derbyshire","mid-derbyshire","66007" ],
    [ "Mid Dorset and North Poole","mid-dorset-and-n-poole","66061" ],
    [ "Mid Norfolk","mid-norfolk","65949" ],
    [ "Mid Sussex","mid-sussex","65999" ],
    [ "Mid Ulster","mid-ulster","66133" ],
    [ "Mid Worcestershire","mid-worcestershire","65888" ],
    [ "Middlesbrough South and East Cleveland","middlesbrough-s-and-e-cle","65657" ],
    [ "Middlesbrough","middlesbrough","65998" ],
    [ "Midlothian","midlothian","14441" ],
    [ "Milton Keynes North","milton-keynes-n","65953" ],
    [ "Milton Keynes South","milton-keynes-s","66076" ],
    [ "Mitcham and Morden","mitcham-and-morden","66038" ],
    [ "Mole Valley","mole-valley","65693" ],
    [ "Monmouth","monmouth","66084" ],
    [ "Montgomeryshire","montgomeryshire","66111" ],
    [ "Moray","moray","14442" ],
    [ "Morecambe and Lunesdale","morecambe-and-lunesdale","65633" ],
    [ "Morley and Outwood","morley-and-outwood","65735" ],
    [ "Motherwell and Wishaw","motherwell-and-wishaw","14443" ],
    [ "North Antrim","n-antrim","66135" ],
    [ "North Ayrshire and Arran","n-ayrshire-and-arran","14445" ],
    [ "North Cornwall","n-cornwall","65602" ],
    [ "North Devon","n-devon","65658" ],
    [ "North Dorset","n-dorset","65702" ],
    [ "North Down","n-down","66136" ],
    [ "North Durham","n-durham","65745" ],
    [ "North East Bedfordshire","n-e-bedfordshire","65855" ],
    [ "North East Cambridgeshire","n-e-cambridgeshire","66063" ],
    [ "North East Derbyshire","n-e-derbyshire","65676" ],
    [ "North East Fife","n-e-fife","14446" ],
    [ "North East Hampshire","n-e-hampshire","65729" ],
    [ "North East Hertfordshire","n-e-hertfordshire","65840" ],
    [ "North East Somerset","n-e-somerset","65619" ],
    [ "North Herefordshire","n-herefordshire","65642" ],
    [ "North Norfolk","n-norfolk","65872" ],
    [ "North Shropshire","n-shropshire","66017" ],
    [ "North Somerset","n-somerset","65817" ],
    [ "North Swindon","n-swindon","65760" ],
    [ "North Thanet","n-thanet","65605" ],
    [ "North Tyneside","n-tyneside","65720" ],
    [ "North West Cambridgeshire","n-w-cambridgeshire","65565" ],
    [ "North West Durham","n-w-durham","65859" ],
    [ "North West Hampshire","n-w-hampshire","65894" ],
    [ "North West Leicestershire","n-w-leicestershire","65776" ],
    [ "North West Norfolk","n-w-norfolk","65713" ],
    [ "North Warwickshire","n-warwickshire","66024" ],
    [ "North Wiltshire","n-wiltshire","65822" ],
    [ "Na h-Eileanan an Iar","na-h-eileanan-an-iar","14444" ],
    [ "Neath","neath","66082" ],
    [ "New Forest East","new-forest-e","65556" ],
    [ "New Forest West","new-forest-w","65815" ],
    [ "Newark","newark","65696" ],
    [ "Newbury","newbury","65862" ],
    [ "Newcastle-under-Lyme","newcastle-under-lyme","65861" ],
    [ "Newcastle upon Tyne Central","newcastle-upon-tyne-centr","66055" ],
    [ "Newcastle upon Tyne East","newcastle-upon-tyne-e","65594" ],
    [ "Newcastle upon Tyne North","newcastle-upon-tyne-n","65664" ],
    [ "Newport East","newport-e","66094" ],
    [ "Newport West","newport-w","66099" ],
    [ "Newry and Armagh","newry-and-armagh","66134" ],
    [ "Newton Abbot","newton-abbot","65828" ],
    [ "Normanton, Pontefract and Castleford","normanton-pontefract-and","65918" ],
    [ "Northampton North","northampton-n","66059" ],
    [ "Northampton South","northampton-s","65910" ],
    [ "Norwich North","norwich-n","65768" ],
    [ "Norwich South","norwich-s","65634" ],
    [ "Nottingham East","nottingham-e","65559" ],
    [ "Nottingham North","nottingham-n","65643" ],
    [ "Nottingham South","nottingham-s","65945" ],
    [ "Nuneaton","nuneaton","65663" ],
    [ "Ochil and South Perthshire","ochil-and-s-perthshire","14447" ],
    [ "Ogmore","ogmore","66107" ],
    [ "Old Bexley and Sidcup","old-bexley-and-sidcup","65653" ],
    [ "Oldham East and Saddleworth","oldham-e-and-saddleworth","65903" ],
    [ "Oldham West and Royton","oldham-w-and-royton","66022" ],
    [ "Orkney and Shetland","orkney-and-shetland","14448" ],
    [ "Orpington","orpington","65682" ],
    [ "Oxford East","oxford-e","66060" ],
    [ "Oxford West and Abingdon","oxford-w-and-abingdon","65564" ],
    [ "Paisley and Renfrewshire North","paisley-and-renfrew-n","14449" ],
    [ "Paisley and Renfrewshire South","paisley-and-renfrew-s","14450" ],
    [ "Pendle","pendle","65668" ],
    [ "Penistone and Stocksbridge","penistone-and-stocksbridg","66002" ],
    [ "Penrith and The Border","penrith-and-the-border","66081" ],
    [ "Perth and North Perthshire","perth-and-n-perthshire","14451" ],
    [ "Peterborough","peterborough","65649" ],
    [ "Plymouth, Moor View","plymouth-moor-view","65974" ],
    [ "Plymouth, Sutton and Devonport","plymouth-sutton-and-devon","65737" ],
    [ "Pontypridd","pontypridd","66087" ],
    [ "Poole","poole","65860" ],
    [ "Poplar and Limehouse","poplar-and-limehouse","65917" ],
    [ "Portsmouth North","portsmouth-n","65566" ],
    [ "Portsmouth South","portsmouth-s","66014" ],
    [ "Preseli Pembrokeshire","preseli-pembrokeshire","66102" ],
    [ "Preston","preston","65673" ],
    [ "Pudsey","pudsey","65637" ],
    [ "Putney","putney","66045" ],
    [ "Rayleigh and Wickford","rayleigh-and-wickford","65795" ],
    [ "Reading East","reading-e","65973" ],
    [ "Reading West","reading-w","65982" ],
    [ "Redcar","redcar","66032" ],
    [ "Redditch","redditch","65700" ],
    [ "Reigate","reigate","66005" ],
    [ "Rhondda","rhondda","66092" ],
    [ "Ribble Valley","ribble-valley","65579" ],
    [ "Richmond Park","richmond-park","65598" ],
    [ "Richmond (Yorks)","richmond-yorks","65722" ],
    [ "Rochdale","rochdale","65843" ],
    [ "Rochester and Strood","rochester-and-strood","66043" ],
    [ "Rochford and Southend East","rochford-and-southend-e","65584" ],
    [ "Romford","romford","66077" ],
    [ "Romsey and Southampton North","romsey-and-southampton-n","65884" ],
    [ "Ross, Skye and Lochaber","ross-skye-and-lochaber","14452" ],
    [ "Rossendale and Darwen","rossendale-and-darwen","66019" ],
    [ "Rother Valley","rother-valley","65930" ],
    [ "Rotherham","rotherham","66029" ],
    [ "Rugby","rugby","65656" ],
    [ "Ruislip, Northwood and Pinner","ruislip-northwood-and-pin","65681" ],
    [ "Runnymede and Weybridge","runnymede-and-weybridge","65589" ],
    [ "Rushcliffe","rushcliffe","65736" ],
    [ "Rutherglen and Hamilton West","rutherglen-and-hamilton-w","14453" ],
    [ "Rutland and Melton","rutland-and-melton","65833" ],
    [ "South Antrim","s-antrim","66137" ],
    [ "South Basildon and East Thurrock","s-basildon-and-e-thurrock","65962" ],
    [ "South Cambridgeshire","s-cambridgeshire","65922" ],
    [ "South Derbyshire","s-derbyshire","65762" ],
    [ "South Dorset","s-dorset","65788" ],
    [ "South Down","s-down","66138" ],
    [ "South East Cambridgeshire","s-e-cambridgeshire","65997" ],
    [ "South East Cornwall","s-e-cornwall","65684" ],
    [ "South Holland and The Deepings","s-holland-and-the-deeping","66051" ],
    [ "South Leicestershire","s-leicestershire","66034" ],
    [ "South Norfolk","s-norfolk","65666" ],
    [ "South Northamptonshire","s-northamptonshire","65902" ],
    [ "South Ribble","s-ribble","65951" ],
    [ "South Shields","s-shields","65719" ],
    [ "South Staffordshire","s-staffordshire","65943" ],
    [ "South Suffolk","s-suffolk","65614" ],
    [ "South Swindon","s-swindon","65800" ],
    [ "South Thanet","s-thanet","65829" ],
    [ "South West Bedfordshire","s-w-bedfordshire","65848" ],
    [ "South West Devon","s-w-devon","65775" ],
    [ "South West Hertfordshire","s-w-hertfordshire","65596" ],
    [ "South West Norfolk","s-w-norfolk","65652" ],
    [ "South West Surrey","s-w-surrey","65678" ],
    [ "South West Wiltshire","s-w-wiltshire","65956" ],
    [ "Saffron Walden","saffron-walden","65654" ],
    [ "Salford and Eccles","salford-and-eccles","65688" ],
    [ "Salisbury","salisbury","65889" ],
    [ "Scarborough and Whitby","scarborough-and-whitby","65891" ],
    [ "Scunthorpe","scunthorpe","66027" ],
    [ "Sedgefield","sedgefield","65763" ],
    [ "Sefton Central","sefton-central","65706" ],
    [ "Selby and Ainsty","selby-and-ainsty","65842" ],
    [ "Sevenoaks","sevenoaks","65698" ],
    [ "Sheffield, Brightside and Hillsborough","sheffield-brightside-and","65601" ],
    [ "Sheffield Central","sheffield-central","65957" ],
    [ "Sheffield, Hallam","sheffield-hallam","65741" ],
    [ "Sheffield, Heeley","sheffield-heeley","65549" ],
    [ "Sheffield South East","sheffield-s-e","65793" ],
    [ "Sherwood","sherwood","65632" ],
    [ "Shipley","shipley","65959" ],
    [ "Shrewsbury and Atcham","shrewsbury-and-atcham","65563" ],
    [ "Sittingbourne and Sheppey","sittingbourne-and-sheppey","65610" ],
    [ "Skipton and Ripon","skipton-and-ripon","65986" ],
    [ "Sleaford and North Hykeham","sleaford-and-n-hykeham","65920" ],
    [ "Slough","slough","65680" ],
    [ "Solihull","solihull","65879" ],
    [ "Somerton and Frome","somerton-and-frome","65812" ],
    [ "Southampton, Itchen","southampton-itchen","66016" ],
    [ "Southampton, Test","southampton-test","65580" ],
    [ "Southend West","southend-w","65876" ],
    [ "Southport","southport","65728" ],
    [ "Spelthorne","spelthorne","65942" ],
    [ "St Albans","st-albans","65715" ],
    [ "St Austell and Newquay","st-austell-and-newquay","65591" ],
    [ "St Helens North","st-helens-n","66073" ],
    [ "St Helens South and Whiston","st-helens-s-and-whiston","65732" ],
    [ "St Ives","st-ives","65854" ],
    [ "Stafford","stafford","66067" ],
    [ "Staffordshire Moorlands","staffordshire-moorlands","65907" ],
    [ "Stalybridge and Hyde","stalybridge-and-hyde","65960" ],
    [ "Stevenage","stevenage","65571" ],
    [ "Stirling","stirling","14454" ],
    [ "Stockport","stockport","65606" ],
    [ "Stockton North","stockton-n","65641" ],
    [ "Stockton South","stockton-s","65908" ],
    [ "Stoke-on-Trent Central","stoke-on-trent-central","65710" ],
    [ "Stoke-on-Trent North","stoke-on-trent-n","65783" ],
    [ "Stoke-on-Trent South","stoke-on-trent-s","65770" ],
    [ "Stone","stone","65950" ],
    [ "Stourbridge","stourbridge","65609" ],
    [ "Strangford","strangford","66139" ],
    [ "Stratford-on-Avon","stratford-on-avon","65648" ],
    [ "Streatham","streatham","66042" ],
    [ "Stretford and Urmston","stretford-and-urmston","65911" ],
    [ "Stroud","stroud","65858" ],
    [ "Suffolk Coastal","suffolk-coastal","65607" ],
    [ "Sunderland Central","sunderland-central","65586" ],
    [ "Surrey Heath","surrey-heath","65747" ],
    [ "Sutton and Cheam","sutton-and-cheam","66040" ],
    [ "Sutton Coldfield","sutton-coldfield","65703" ],
    [ "Swansea East","swansea-e","66091" ],
    [ "Swansea West","swansea-w","66118" ],
    [ "Tamworth","tamworth","65880" ],
    [ "Tatton","tatton","65964" ],
    [ "Taunton Deane","taunton-deane","65767" ],
    [ "Telford","telford","65992" ],
    [ "Tewkesbury","tewkesbury","65976" ],
    [ "The Cotswolds","the-cotswolds","65789" ],
    [ "The Wrekin","the-wrekin","65977" ],
    [ "Thirsk and Malton","thirsk-and-malton","65686" ],
    [ "Thornbury and Yate","thornbury-and-yate","65905" ],
    [ "Thurrock","thurrock","65919" ],
    [ "Tiverton and Honiton","tiverton-and-honiton","65761" ],
    [ "Tonbridge and Malling","tonbridge-and-malling","65744" ],
    [ "Tooting","tooting","65554" ],
    [ "Torbay","torbay","65692" ],
    [ "Torfaen","torfaen","66104" ],
    [ "Torridge and West Devon","torridge-and-w-devon","65904" ],
    [ "Totnes","totnes","65810" ],
    [ "Tottenham","tottenham","66074" ],
    [ "Truro and Falmouth","truro-and-falmouth","65659" ],
    [ "Tunbridge Wells","tunbridge-wells","65660" ],
    [ "Twickenham","twickenham","65782" ],
    [ "Tynemouth","tynemouth","65868" ],
    [ "Upper Bann","upper-bann","66140" ],
    [ "Uxbridge and South Ruislip","uxbridge-and-s-ruislip","65613" ],
    [ "Vale of Clwyd","vale-of-clwyd","66116" ],
    [ "Vale of Glamorgan","vale-of-glamorgan","66098" ],
    [ "Vauxhall","vauxhall","65825" ],
    [ "West Aberdeenshire and Kincardine","w-aberdeenshire-and-kinca","14455" ],
    [ "West Bromwich East","w-bromwich-e","65983" ],
    [ "West Bromwich West","w-bromwich-west","66047" ],
    [ "West Dorset","w-dorset","65716" ],
    [ "West Dunbartonshire","w-dunbartonshire","14456" ],
    [ "West Ham","w-ham","66058" ],
    [ "West Lancashire","w-lancashire","65873" ],
    [ "West Suffolk","w-suffolk","65629" ],
    [ "West Tyrone","w-tyrone","66141" ],
    [ "West Worcestershire","w-worcestershire","65758" ],
    [ "Wakefield","wakefield","65733" ],
    [ "Wallasey","wallasey","65635" ],
    [ "Walsall North","walsall-n","65890" ],
    [ "Walsall South","walsall-s","65832" ],
    [ "Walthamstow","walthamstow","65651" ],
    [ "Wansbeck","wansbeck","65631" ],
    [ "Wantage","wantage","65638" ],
    [ "Warley","warley","66079" ],
    [ "Warrington North","warrington-n","65874" ],
    [ "Warrington South","warrington-s","65916" ],
    [ "Warwick and Leamington","warwick-and-leamington","65608" ],
    [ "Washington and Sunderland West","washington-and-sunderland","66049" ],
    [ "Watford","watford","65626" ],
    [ "Waveney","waveney","66004" ],
    [ "Wealden","wealden","65961" ],
    [ "Weaver Vale","weaver-vale","65769" ],
    [ "Wellingborough","wellingborough","65830" ],
    [ "Wells","wells","65560" ],
    [ "Welwyn Hatfield","welwyn-hatfield","65740" ],
    [ "Wentworth and Dearne","wentworth-and-dearne","65588" ],
    [ "Westminster North","westminster-n","65851" ],
    [ "Westmorland and Lonsdale","westmorland-and-lonsdale","65963" ],
    [ "Weston-Super-Mare","weston-super-mare","65742" ],
    [ "Wigan","wigan","65612" ],
    [ "Wimbledon","wimbledon","65827" ],
    [ "Winchester","winchester","65921" ],
    [ "Windsor","windsor","65552" ],
    [ "Wirral South","wirral-s","65847" ],
    [ "Wirral West","wirral-w","65897" ],
    [ "Witham","witham","65831" ],
    [ "Witney","witney","65622" ],
    [ "Woking","woking","66039" ],
    [ "Wokingham","wokingham","65774" ],
    [ "Wolverhampton North East","wolverhampton-n-e","65777" ],
    [ "Wolverhampton South East","wolverhampton-s-e","65593" ],
    [ "Wolverhampton South West","wolverhampton-s-w","65948" ],
    [ "Worcester","worcester","65577" ],
    [ "Workington","workington","65625" ],
    [ "Worsley and Eccles South","worsley-and-eccles-s","65757" ],
    [ "Worthing West","worthing-w","65562" ],
    [ "Wrexham","wrexham","66113" ],
    [ "Wycombe","wycombe","66010" ],
    [ "Wyre and Preston North","wyre-and-preston-n","65695" ],
    [ "Wyre Forest","wyre-forest","66078" ],
    [ "Wythenshawe and Sale East","wythenshawe-and-sale-e","65669" ],
    [ "Yeovil","yeovil","65935" ],
    [ "Ynys Môn","ynys-mon","66115" ],
    [ "York Central","york-central","65965" ],
    [ "York Outer","york-outer","66037" ]
  ]

  def getConstituency(postcode)
    pc = UKPostcode.new(postcode)
    if not pc.valid?
      return false
    end
    uri = 'http://mapit.mysociety.org/postcode/'+pc.outcode+pc.incode
    jsondata = open(uri)
    return JSON.load(jsondata)
  end

  def getMPid(candidate)
    # Is the best way to check this to look at the public whip identifier?
    for ide in candidate['identifiers']
      if ide['scheme'] == 'uk.org.publicwhip'
        # return numbers from end of the string
        return /[0-9]+$/.match(ide['identifier'])[0]
      end
    end
    return nil
  end

  def getPolicy(candidate, policyArea)
    party = candidate['party_memberships']['2015']['name']
    if not PARTY_CONSTANTS.key?(party)
      party = 'Default'
    end
    return PARTY_CONSTANTS[party][policyArea]
  end

  def getAllPolicies(candidates)
    policies = Hash.new
    for candidate in candidates
      policies[candidate['id']] = Hash.new
      for policy in POLICY_AREAS
        policies[candidate['id']][policy] = getPolicy(candidate, policy)
      end
    end
    return policies
  end

  def getImageUrl(candidate, twitter_obj)
    if candidate['image']
      return candidate['image']
    end
    if candidate['twitter_username'].length > 2
      begin
        twitter_user = twitter_obj.user(candidate['twitter_username'])
      rescue Twitter::Error::NotFound
        candidate['twitter_username'] = ''
        return nil
      end
      twitter_profile_uri = twitter_user.profile_image_uri.to_s.sub("_normal", "")
      if not twitter_profile_uri =~ /default_profile_images/
        return twitter_profile_uri
      end
    end
  end

  def isEmptyCandidate(c)
    if c['MPid']
      return false
    elsif c['twitter_username'] and c['twitter_username'].length > 2
      return false
    elsif c['facebook_personal_url'] and c['facebook_personal_url'].length > 5
      return false
    elsif c['homepage_url'] and c['homepage_url'].length > 5
      return false
    elsif c['party_ppc_page_url'] and c['party_ppc_page_url'].length > 5
      return false
    elsif c['wikipedia_url'] and c['wikipedia_url'].length > 5
      return false
    elsif c['email'] and c['email'].length > 5
      return false
    end
    return true
  end

  def getCandidates(constituencyId)
    uri = 'http://yournextmp.popit.mysociety.org/api/v0.1/posts/'+constituencyId.to_s+'?embed=membership.person'
    twitter_client = Twitter::REST::Client.new do |config|
      config.consumer_key = 'vzUdH63VDtZX1AQiUNBPpL0Sj'
      config.consumer_secret = 'gosJYtqmDduobc4QWVo4xL56ykro1sBvQlVbZVnuHwkxhwZFVd'
      config.access_token = '3006172181-DiGGfRtjGyHvwpl1k8jaR4o3uPEW2GQRdZwLwB0'
      config.access_token_secret = 'MCmGUPGi4jpMZS7795FRGp6JXdtDKwNr8EedbMzUY4JOA'
    end
    c = Twitter::REST::Client.new do |config|
      config.consumer_key = '8m0D3VLDUjCMTREtMsQ6WKWQC'
      config.consumer_secret = 'XcEtBqAI6TTEwiwgRMwTSpEG2CN4jZnh8FxaC9XDKaKeKvVFma'
      config.access_token = '3006172181-etu5wtNStpIAdc6SnkmBZGMkqJ65Y03qpcrQdW4'
      config.access_token_secret = 'ClyV9cs4ETf5o3S49fwVm9UwFGZiORNKOla5AJaM8Jnz7'
    end

    jsondata = open(uri)
    @data = JSON.load(jsondata)
    @candidates = []
    for cand in @data['result']['memberships']
      @currentConstituency = cand['person_id']['versions'][0]['data']['standing_in']['2015']
      if @currentConstituency and @currentConstituency['post_id'] == constituencyId.to_s
        # merge to make sure versions[0][data] is easily accessible in object - not ideal!
        @candidates.concat([cand['person_id']['versions'][0]['data'].merge(cand['person_id'])])
      end
    end
    # For some reason there are duplicates in the JSON
    @candidates = @candidates.uniq
    for i in @candidates.each_index()
      @candidates[i]['image_url'] = getImageUrl(@candidates[i], twitter_client)
      @candidates[i]['party'] = @candidates[i]['party_memberships']['2015']['name']
      @candidates[i]['isEmpty'] = isEmptyCandidate(@candidates[i])
      if PARTY_CONSTANTS[@candidates[i]['party']]
        @candidates[i]['party_image_uri'] = PARTY_CONSTANTS[@candidates[i]['party']]['party_image_uri']
      else
        @candidates[i]['party_image_uri'] = nil
      end
      @candidates[i]['MPid'] = getMPid(@candidates[i])
    end
    return @candidates
  end

  def getCandidateById(id)
    uri = 'http://yournextmp.popit.mysociety.org/api/v0.1/search/persons?q=id:'+id.to_s
    jsondata = open(uri)
    @data = JSON.load(jsondata)
    return @data['result'][0]
  end

  def index
    @q = request['q']
    @condata = getConstituency(@q)
    if not @condata
      # flash[:alert] = "Invalid post code, please try again"
      redirect_to "/?error" and return
    end
    @conId = @condata['shortcuts']['WMC']
    @constituency = @condata['areas'][@conId.to_s]
    @twitter_list = TWITTER_LIST[@conId]
    @candidates = getCandidates(@conId)
    @policies = getAllPolicies(@candidates)
    @PARTY_CONSTANTS = PARTY_CONSTANTS
  end

  def constituencies
    @constituency_list = CONSTITUENCY_LIST
  end

  def show
    @candidate = getCandidateById(request['id'])
  end
end
